### ISSUE TITLE
Anyone care to enlighten me as to what the problem is? One problem a day ~ one solution and another

### ISSUE THREAD

**Issue by wuliang19869312** [cocktailpeanut/fluxgym#106]
Traceback (most recent call last):
  File "D:\fluxgym\env\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fluxgym\env\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fluxgym\env\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fluxgym\env\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fluxgym\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fluxgym\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\fluxgym\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\fluxgym\app.py", line 255, in create_dataset
    file.write(original_caption)
UnicodeEncodeError: 'gbk' codec can't encode character '\xe4' in position 109: illegal multibyte sequence

**Comment by 6Morpheus6** [comment]
@wuliang19869312  Is it with the current fluxgym app? Cocktailpeanut fixed it in the last version.
Please update fluxgym and try again.
If it still doesn't work, check your captions for special characters and remove or replace them please.
