### ISSUE TITLE
can not train

### ISSUE THREAD

**Issue by zrxpower** [cocktailpeanut/fluxgym#113]
`(env) D:\FLUX_TRAINING\fluxgym\outputs>cd pix2

(env) D:\FLUX_TRAINING\fluxgym\outputs\pix2>train.bat

(env) D:\FLUX_TRAINING\fluxgym\outputs\pix2>accelerate launch   --mixed_precision bf16   --num_cpu_threads_per_process 1   sd-scripts/flux_train_network.py   --pretrained_model_name_or_path "D:\FLUX_TRAINING\fluxgym\models\unet\flux1-dev.sft"   --clip_l "D:\FLUX_TRAINING\fluxgym\models\clip\clip_l.safetensors"   --t5xxl "D:\FLUX_TRAINING\fluxgym\models\clip\t5xxl_fp16.safetensors"   --ae "D:\FLUX_TRAINING\fluxgym\models\vae\ae.sft"   --cache_latents_to_disk   --save_model_as safetensors   --sdpa --persistent_data_loader_workers   --max_data_loader_n_workers 2   --seed 42   --gradient_checkpointing   --mixed_precision bf16   --save_precision bf16   --network_module networks.lora_flux   --network_dim 4   --optimizer_type adafactor   --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False"   --split_mode   --network_args "train_blocks=single"   --lr_scheduler constant_with_warmup   --max_grad_norm 0.0 --sample_prompts="D:\FLUX_TRAINING\fluxgym\outputs\pix2\sample_prompts.txt" --sample_every_n_steps="100"   --learning_rate 8e-4   --cache_text_encoder_outputs   --cache_text_encoder_outputs_to_disk   --fp8_base   --highvram   --max_train_epochs 16   --save_every_n_epochs 4   --dataset_config "D:\FLUX_TRAINING\fluxgym\outputs\pix2\dataset.toml"   --output_dir "D:\FLUX_TRAINING\fluxgym\outputs\pix2"   --output_name pix2   --timestep_sampling shift   --discrete_flow_shift 3.1582   --model_prediction_type raw   --guidance_scale 1   --loss_type l2
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "D:\FLUX_TRAINING\fluxgym\outputs\pix2\sd-scripts\flux_train_network.py", line 14, in <module>
    import train_network
ModuleNotFoundError: No module named 'train_network'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\FLUX_TRAINING\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\FLUX_TRAINING\fluxgym\env\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\FLUX_TRAINING\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "D:\FLUX_TRAINING\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\FLUX_TRAINING\\fluxgym\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'D:\\FLUX_TRAINING\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'D:\\FLUX_TRAINING\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'D:\\FLUX_TRAINING\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'D:\\FLUX_TRAINING\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--sample_prompts=D:\\FLUX_TRAINING\\fluxgym\\outputs\\pix2\\sample_prompts.txt', '--sample_every_n_steps=100', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'D:\\FLUX_TRAINING\\fluxgym\\outputs\\pix2\\dataset.toml', '--output_dir', 'D:\\FLUX_TRAINING\\fluxgym\\outputs\\pix2', '--output_name', 'pix2', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.`

**Comment by zrxpower** [comment]
take me long time but i cant find the mistake,i follow the website step by step.

**Comment by zrxpower** [comment]
> [2024-09-20 07:07:05] [INFO] Running D:\FLUX_TRAINING\fluxgym\outputs\pix3\train.bat
[2024-09-20 07:07:05] [INFO] 
[2024-09-20 07:07:05] [INFO] (env) D:\FLUX_TRAINING\fluxgym>accelerate launch   --mixed_precision bf16   --num_cpu_threads_per_process 1   sd-scripts/flux_train_network.py   --pretrained_model_name_or_path "D:\FLUX_TRAINING\fluxgym\models\unet\flux1-dev.sft"   --clip_l "D:\FLUX_TRAINING\fluxgym\models\clip\clip_l.safetensors"   --t5xxl "D:\FLUX_TRAINING\fluxgym\models\clip\t5xxl_fp16.safetensors"   --ae "D:\FLUX_TRAINING\fluxgym\models\vae\ae.sft"   --cache_latents_to_disk   --save_model_as safetensors   --sdpa --persistent_data_loader_workers   --max_data_loader_n_workers 2   --seed 42   --gradient_checkpointing   --mixed_precision bf16   --save_precision bf16   --network_module networks.lora_flux   --network_dim 4   --optimizer_type adafactor   --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False"   --split_mode   --network_args "train_blocks=single"   --lr_scheduler constant_with_warmup   --max_grad_norm 0.0 --sample_prompts="D:\FLUX_TRAINING\fluxgym\outputs\pix3\sample_prompts.txt" --sample_every_n_steps="600"   --learning_rate 8e-4   --cache_text_encoder_outputs   --cache_text_encoder_outputs_to_disk   --fp8_base   --highvram   --max_train_epochs 16   --save_every_n_epochs 4   --dataset_config "D:\FLUX_TRAINING\fluxgym\outputs\pix3\dataset.toml"   --output_dir "D:\FLUX_TRAINING\fluxgym\outputs\pix3"   --output_name pix3   --timestep_sampling shift   --discrete_flow_shift 3.1582   --model_prediction_type raw   --guidance_scale 1   --loss_type l2
[2024-09-20 07:07:09] [INFO] The following values were not passed to `accelerate launch` and had defaults used instead:
[2024-09-20 07:07:09] [INFO] `--num_processes` was set to a value of `1`
[2024-09-20 07:07:09] [INFO] `--num_machines` was set to a value of `1`
[2024-09-20 07:07:09] [INFO] `--dynamo_backend` was set to a value of `'no'`
[2024-09-20 07:07:09] [INFO] To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-09-20 07:07:12] [INFO] highvram is enabled / highvramが有効です
[2024-09-20 07:07:12] [INFO] 2024-09-20 07:07:12 WARNING  cache_latents_to_disk is        train_util.py:3951
[2024-09-20 07:07:12] [INFO] enabled, so cache_latents is
[2024-09-20 07:07:12] [INFO] also enabled /
[2024-09-20 07:07:12] [INFO] cache_latents_to_diskが有効なた
[2024-09-20 07:07:12] [INFO] め、cache_latentsを有効にします
[2024-09-20 07:07:12] [INFO] 2024-09-20 07:07:12 INFO     t5xxl_max_token_length:  flux_train_network.py:155
[2024-09-20 07:07:12] [INFO] 512
[2024-09-20 07:07:13] [INFO] D:\FLUX_TRAINING\fluxgym\env\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
[2024-09-20 07:07:13] [INFO] warnings.warn(
[2024-09-20 07:07:13] [INFO] You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
[2024-09-20 07:07:13] [INFO] 2024-09-20 07:07:13 INFO     Loading dataset config from   train_network.py:280
[2024-09-20 07:07:13] [INFO] D:\FLUX_TRAINING\fluxgym\outp
[2024-09-20 07:07:13] [INFO] uts\pix3\dataset.toml
[2024-09-20 07:07:13] [INFO] INFO     prepare images.                 train_util.py:1808
[2024-09-20 07:07:13] [INFO] INFO     get image size from name of     train_util.py:1746
[2024-09-20 07:07:13] [INFO] cache files
[2024-09-20 07:07:13] [INFO] 0%|          | 0/21 [00:00<?, ?it/s]
100%|██████████| 21/21 [00:00<00:00, 10470.80it/s]
[2024-09-20 07:07:13] [INFO] INFO     set image size from cache       train_util.py:1753
[2024-09-20 07:07:13] [INFO] files: 0/21
[2024-09-20 07:07:13] [INFO] INFO     found directory                 train_util.py:1755
[2024-09-20 07:07:13] [INFO] D:\FLUX_TRAINING\fluxgym\datase
[2024-09-20 07:07:13] [INFO] ts\pix3 contains 21 image files
[2024-09-20 07:07:13] [INFO] ERROR    illegal char in file (not       train_util.py:1703
[2024-09-20 07:07:13] [INFO] UTF-8) /
[2024-09-20 07:07:13] [INFO] ファイルにUTF-8以外の文字があり
[2024-09-20 07:07:13] [INFO] ます:
[2024-09-20 07:07:13] [INFO] D:\FLUX_TRAINING\fluxgym\datase
[2024-09-20 07:07:13] [INFO] ts\pix3\013.txt
[2024-09-20 07:07:13] [INFO] Traceback (most recent call last):
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\sd-scripts\flux_train_network.py", line 519, in <module>
[2024-09-20 07:07:13] [INFO] trainer.train(args)
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\sd-scripts\train_network.py", line 317, in train
[2024-09-20 07:07:13] [INFO] train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
[2024-09-20 07:07:13] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\sd-scripts\library\config_util.py", line 485, in generate_dataset_group_by_blueprint
[2024-09-20 07:07:13] [INFO] dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
[2024-09-20 07:07:13] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\sd-scripts\library\train_util.py", line 1825, in __init__
[2024-09-20 07:07:13] [INFO] img_paths, captions, sizes = load_dreambooth_dir(subset)
[2024-09-20 07:07:13] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\sd-scripts\library\train_util.py", line 1765, in load_dreambooth_dir
[2024-09-20 07:07:13] [INFO] cap_for_img = read_caption(img_path, subset.caption_extension, subset.enable_wildcard)
[2024-09-20 07:07:13] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\sd-scripts\library\train_util.py", line 1704, in read_caption
[2024-09-20 07:07:13] [INFO] raise e
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\sd-scripts\library\train_util.py", line 1701, in read_caption
[2024-09-20 07:07:13] [INFO] lines = f.readlines()
[2024-09-20 07:07:13] [INFO] ^^^^^^^^^^^^^
[2024-09-20 07:07:13] [INFO] File "<frozen codecs>", line 322, in decode
[2024-09-20 07:07:13] [INFO] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 86: invalid start byte
[2024-09-20 07:07:13] [INFO] Traceback (most recent call last):
[2024-09-20 07:07:13] [INFO] File "<frozen runpy>", line 198, in _run_module_as_main
[2024-09-20 07:07:13] [INFO] File "<frozen runpy>", line 88, in _run_code
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\env\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-20 07:07:13] [INFO] args.func(args)
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-20 07:07:13] [INFO] simple_launcher(args)
[2024-09-20 07:07:13] [INFO] File "D:\FLUX_TRAINING\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-20 07:07:13] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-20 07:07:13] [INFO] subprocess.CalledProcessError: Command '['D:\\FLUX_TRAINING\\fluxgym\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'D:\\FLUX_TRAINING\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'D:\\FLUX_TRAINING\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'D:\\FLUX_TRAINING\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'D:\\FLUX_TRAINING\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--sample_prompts=D:\\FLUX_TRAINING\\fluxgym\\outputs\\pix3\\sample_prompts.txt', '--sample_every_n_steps=600', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'D:\\FLUX_TRAINING\\fluxgym\\outputs\\pix3\\dataset.toml', '--output_dir', 'D:\\FLUX_TRAINING\\fluxgym\\outputs\\pix3', '--output_name', 'pix3', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-09-20 07:07:14] [ERROR] Command exited with code 1
[2024-09-20 07:07:14] [INFO] Runner: <LogsViewRunner nb_logs=71 exit_code=1>

**Comment by zrxpower** [comment]
ALSO A NEW ENV AND NEW GYM TASK
