### ISSUE TITLE
Error Maj : voluptuous

### ISSUE THREAD

**Issue by XT-404** [cocktailpeanut/fluxgym#122]
H:\fluxgym>python app.py
Traceback (most recent call last):
  File "H:\fluxgym\app.py", line 21, in <module>
    import train_network
  File "H:\fluxgym\sd-scripts\train_network.py", line 26, in <module>
    import library.config_util as config_util
  File "H:\fluxgym\sd-scripts\library\config_util.py", line 22, in <module>
    import voluptuous
ModuleNotFoundError: No module named 'voluptuous'

**Comment by fahadshery** [comment]
you need to activate the python `env`:
```
python -m venv env
env\Scripts\activate
```
if `python` command is not found, then try `python3`...if still doesn't work then  make sure python is installed on your computer...

**Comment by XT-404** [comment]
@fahadshery not a bad joke, my python is good, I even reinstalled the complete code with the new update, same problem with the update and burst
