### ISSUE TITLE
[ERROR] Command exited with code 1

### ISSUE THREAD

**Issue by lesteryebin** [cocktailpeanut/fluxgym#129]
2024-09-25 22:05:24] [INFO] w.start()
[2024-09-25 22:05:24] [INFO] File "multiprocessing\process.py", line 121, in start
[2024-09-25 22:05:24] [INFO] File "multiprocessing\context.py", line 224, in _Popen
[2024-09-25 22:05:24] [INFO] File "multiprocessing\context.py", line 336, in _Popen
[2024-09-25 22:05:24] [INFO] File "multiprocessing\popen_spawn_win32.py", line 75, in __init__
[2024-09-25 22:05:24] [INFO] FileNotFoundError: [WinError 3] 系统找不到指定的路径。
[2024-09-25 22:05:24] [INFO] steps:   0%|          | 0/1440 [00:00<?, ?it/s]
[2024-09-25 22:05:25] [INFO] Traceback (most recent call last):
[2024-09-25 22:05:25] [INFO] File "<frozen runpy>", line 198, in _run_module_as_main
[2024-09-25 22:05:25] [INFO] File "<frozen runpy>", line 88, in _run_code
[2024-09-25 22:05:25] [INFO] File "E:\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-25 22:05:25] [INFO] File "E:\fluxgym\env\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-25 22:05:25] [INFO] args.func(args)
[2024-09-25 22:05:25] [INFO] File "E:\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-25 22:05:25] [INFO] simple_launcher(args)
[2024-09-25 22:05:25] [INFO] File "E:\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-25 22:05:25] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-25 22:05:25] [INFO] subprocess.CalledProcessError: Command '['E:\\fluxgym\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'E:\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'E:\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'E:\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'E:\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--sample_prompts=E:\\fluxgym\\outputs\\vivian\\sample_prompts.txt', '--sample_every_n_steps=100', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'E:\\fluxgym\\outputs\\vivian\\dataset.toml', '--output_dir', 'E:\\fluxgym\\outputs\\vivian', '--output_name', 'vivian', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-09-25 22:05:26] [ERROR] Command exited with code 1
[2024-09-25 22:05:26] [INFO] Runner: <LogsViewRunner nb_logs=214 exit_code=1>

**Comment by Steinix75** [comment]
Try to use shorter image captions, possibly without special characters. This worked for me.
