### ISSUE TITLE
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'M:\\fluxgym\\outputs\\baoguoabc\\sample'

### ISSUE THREAD

**Issue by sunyiwk** [cocktailpeanut/fluxgym#142]
Creating dataset
resize datasets/baoguoabc\1 6.jpg : 512x512
image_path=datasets/baoguoabc\1 6.jpg, caption_path = M:\fluxgym\datasets\baoguoabc\1 6.txt, original_caption=baoguoabc1
resize datasets/baoguoabc\1 7.jpg : 512x512
image_path=datasets/baoguoabc\1 7.jpg, caption_path = M:\fluxgym\datasets\baoguoabc\1 7.txt, original_caption=baoguoabc1
resize datasets/baoguoabc\1 8.jpg : 512x512
image_path=datasets/baoguoabc\1 8.jpg, caption_path = M:\fluxgym\datasets\baoguoabc\1 8.txt, original_caption=baoguoabc1
resize datasets/baoguoabc\1 9.jpg : 512x512
image_path=datasets/baoguoabc\1 9.jpg, caption_path = M:\fluxgym\datasets\baoguoabc\1 9.txt, original_caption=baoguoabc1
resize datasets/baoguoabc\1 10.jpg : 512x512
image_path=datasets/baoguoabc\1 10.jpg, caption_path = M:\fluxgym\datasets\baoguoabc\1 10.txt, original_caption=baoguoabc1
destination_folder datasets/baoguoabc
concept_sentence=baoguoabc1
lora_name baoguoabc, concept_sentence=baoguoabc1, output_name=baoguoabc
license_items=['license: other', 'license_name: flux-1-dev-non-commercial-license', 'license_link: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/LICENSE.md']
license_str = license: other
license_name: flux-1-dev-non-commercial-license
license_link: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/LICENSE.md
Traceback (most recent call last):
  File "M:\fluxgym\env\Lib\site-packages\gradio\queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\gradio\blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 671, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "M:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 809, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "M:\fluxgym\app.py", line 625, in start_training
    md = readme(base_model, lora_name, concept_sentence, sample_prompts)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\fluxgym\app.py", line 60, in readme
    for filename in os.listdir(samples_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'M:\\fluxgym\\outputs\\baoguoabc\\sample'

**Comment by Mixomo** [comment]
same error!

**Comment by ILikeToasters** [comment]
I had an issue after making my captions longer in a dataset that worked previously. Once I shortened the captions it worked without error.

**Comment by ILikeToasters** [comment]
So after trying to verify that was the issue I have now run into the error again. And just to understand I am using my own txt files for captions and dropping them in with the images in the UI which worked fine with the same dataset 4 times previously and the only change has been to the actual captions. Attached both logs from UI and terminal. 

[terminal log.txt](https://github.com/user-attachments/files/17176898/terminal.log.txt)
[ui log.txt](https://github.com/user-attachments/files/17176899/ui.log.txt)

**Comment by Mixomo** [comment]
Pinokio seems like an all-in-one solution for AI setup and management, but lately it's been a mess. 
It's appreciated that it's free and the huge effort behind it, but these errors are a real pain.

**Comment by Mixomo** [comment]
Pinokio seems like an all-in-one solution for AI setup and management, but lately it's been a mess. 
It's appreciated that it's free and the huge effort behind it, but these errors are a real pain.

**Comment by cocktailpeanut** [comment]
@Mixomo This has nothing to do with pinokio. it's just an issue with fluxgym. Meaning you would have the exact same issue if you installed Fluxgym manually (which is also mentioned on the README). Please be civil.

I am going to look into this.

**Comment by cocktailpeanut** [comment]
> So after trying to verify that was the issue I have now run into the error again. And just to understand I am using my own txt files for captions and dropping them in with the images in the UI which worked fine with the same dataset 4 times previously and the only change has been to the actual captions. Attached both logs from UI and terminal. I do notice when I look in the dataset folder after it starts one of the txt files will be blank.
> 
> [terminal log.txt](https://github.com/user-attachments/files/17176898/terminal.log.txt) [ui log.txt](https://github.com/user-attachments/files/17176899/ui.log.txt)

If you compare your log and the OP's log it's clear that these are completely different issues. This is why having access to the full logs is important.

OP's case happens when it tries to generate the README file, and the error message is `FileNotFoundError`, whereas in your case the error is not about file not found, but `AssertionError: caption file is empty`. They are completely different issues. Can you create a new standalone issue for your case with the logs again? Thanks.

**Comment by ILikeToasters** [comment]
> > So after trying to verify that was the issue I have now run into the error again. And just to understand I am using my own txt files for captions and dropping them in with the images in the UI which worked fine with the same dataset 4 times previously and the only change has been to the actual captions. Attached both logs from UI and terminal. I do notice when I look in the dataset folder after it starts one of the txt files will be blank.
> > [terminal log.txt](https://github.com/user-attachments/files/17176898/terminal.log.txt) [ui log.txt](https://github.com/user-attachments/files/17176899/ui.log.txt)
> 
> If you compare your log and the OP's log it's clear that these are completely different issues. This is why having access to the full logs is important.
> 
> OP's case happens when it tries to generate the README file, and the error message is `FileNotFoundError`, whereas in your case the error is not about file not found, but `AssertionError: caption file is empty`. They are completely different issues. Can you create a new standalone issue for your case with the logs again? Thanks.

Done.

**Comment by agoodis** [comment]
I encountered a UnicodeDecodeError during LoRA training with FluxGym due to non-UTF8 characters in the .txt files

**Comment by cocktailpeanut** [comment]
> The issue you faced in FluxGym during LoRA training is related to non-UTF8 characters in your .txt files, which can cause the training to fail with a UnicodeDecodeError. This error arises when files contain characters that are not compatible with UTF-8 encoding.

@agoodis please post the full logs, just like OP posted. I need to know exactly when this happens. The error you posted can happen during multiple different stages so just this error message alone doesn't give enough info.

**Comment by Friedrish933** [comment]
Hello, I have the same problem; the "sample" folder is not being created. I then had the error "FileNotFoundError: [WinError 3]", but when I manually create the "sample" folder, the error is "IndexError: list index out of range."

![image](https://github.com/user-attachments/assets/f4884492-584d-4516-8f4f-ce2a09c6f63c)

please tel me if you need logs

**Comment by signerzwb** [comment]
我遇到过这个问题，发现问题在于反推出来的关键字里有特殊字符，造成了这个错误，检查一下所有图片相关的关键字有没有比如，法语，奇怪的字符串，上次就是一个法语影响了不能运行，去掉就好了。
I have encountered this issue before and found that the problem lies in the presence of special characters in the reverse deduced keywords, which caused this error. Please check if there are any keywords related to the images, such as French or strange strings. Last time, it was just French that affected the operation, so just remove it.

**Comment by signerzwb** [comment]
> Hello, I have the same problem; the "sample" folder is not being created. I then had the error "FileNotFoundError: [WinError 3]", but when I manually create the "sample" folder, the error is "IndexError: list index out of range."
> 
> ![image](https://private-user-images.githubusercontent.com/46425048/371865582-f4884492-584d-4516-8f4f-ce2a09c6f63c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MjQ5MzEsIm5iZiI6MTcyNzYyNDYzMSwicGF0aCI6Ii80NjQyNTA0OC8zNzE4NjU1ODItZjQ4ODQ0OTItNTg0ZC00NTE2LThmNGYtY2UyYTA5YzZmNjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDE1NDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NDhiZDU2NDg5NTJlZDE2NTY3YWM4ZTFiZTNmMjAwNDFiOWYxNDEyYTFiNzUwMjdjZDc1Yjk0Njc1YjdjNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uydcJVU2xl0ldcNfDtySlGaz5MI4nGOPcwJTUkx_bb8)
> 
> please tel me if you need logs
> 
> **#133**

Don't try the reverse function first. Keep all image keywords as default. If it can run, check if there are any special characters in the keywords, such as French

**Comment by Friedrish933** [comment]
@signerzwb how can i check presence of special characters in the reverse deduced keywords ?
My path is C:\Users\flope\fluxgym\datasets\elinat1
And picture names are 4.PNG and 5.PNG

**Comment by cocktailpeanut** [comment]
OK guys I think this was happening when you do NOT set the "sample image every N steps" (by default it's 0), or if your "sample image prompts" is empty, when creating the README file.

I just pushed an update that doesn't look for the sample folder when the above fields are not set.

**Please try reinstalling from scratch and try again** and let me know (You could just update too, but just to make sure everything is clean)
