### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mertayd0** [cocktailpeanut/fluxgym#143]
Traceback (most recent call last):
  File "F:\fluxgym\env\Lib\site-packages\gradio\queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\gradio\blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 671, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "F:\fluxgym\env\Lib\site-packages\gradio\utils.py", line 809, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "F:\fluxgym\app.py", line 625, in start_training
    md = readme(base_model, lora_name, concept_sentence, sample_prompts)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\fluxgym\app.py", line 73, in readme
    _, _, image_path = final_sample_image_paths[i]
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by BosonHair** [comment]
I have the same issue on an m2 Mac Studio.

**Comment by taozhiyuai** [comment]
@BosonHair @mertayd0   run on MAC successfully now?

**Comment by BosonHair** [comment]
For me, yes

**Comment by taozhiyuai** [comment]
@BosonHair please help this issue from me. https://github.com/cocktailpeanut/fluxgym#issue-2639562787

thanks.

**Comment by taozhiyuai** [comment]
> For me, yes

train on MPS or CPU?
