### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sunyiwk** [cocktailpeanut/fluxgym#146]
[2024-09-29 06:45:14] [INFO] flux_train_utils.sample_images(
[2024-09-29 06:45:14] [INFO] File "M:\fluxgym\sd-scripts\library\flux_train_utils.py", line 90, in sample_images
[2024-09-29 06:45:14] [INFO] sample_image_inference(
[2024-09-29 06:45:14] [INFO] File "M:\fluxgym\sd-scripts\library\flux_train_utils.py", line 229, in sample_image_inference
[2024-09-29 06:45:14] [INFO] x = denoise(flux, noise, img_ids, t5_out, txt_ids, l_pooled, timesteps=timesteps, guidance=scale, t5_attn_mask=t5_attn_mask)
[2024-09-29 06:45:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-29 06:45:14] [INFO] File "M:\fluxgym\sd-scripts\library\flux_train_utils.py", line 316, in denoise
[2024-09-29 06:45:14] [INFO] model.prepare_block_swap_before_forward()
[2024-09-29 06:45:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-29 06:45:14] [INFO] File "M:\fluxgym\env\Lib\site-packages\torch\nn\modules\module.py", line 1729, in __getattr__
[2024-09-29 06:45:14] [INFO] raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[2024-09-29 06:45:14] [INFO] AttributeError: 'FluxUpperLowerWrapper' object has no attribute 'prepare_block_swap_before_forward'
[2024-09-29 06:45:15] [INFO] steps:  16%|█▌        | 100/640 [20:06<1:48:34, 12.06s/it, avr_loss=0.321]
[2024-09-29 06:45:21] [INFO] Traceback (most recent call last):
[2024-09-29 06:45:21] [INFO] File "<frozen runpy>", line 198, in _run_module_as_main
[2024-09-29 06:45:21] [INFO] File "<frozen runpy>", line 88, in _run_code
[2024-09-29 06:45:21] [INFO] File "M:\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-29 06:45:21] [INFO] File "M:\fluxgym\env\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-29 06:45:22] [INFO] args.func(args)
[2024-09-29 06:45:22] [INFO] File "M:\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-29 06:45:22] [INFO] simple_launcher(args)
[2024-09-29 06:45:22] [INFO] File "M:\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-29 06:45:22] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-29 06:45:22] [INFO] subprocess.CalledProcessError: Command '['M:\\fluxgym\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'M:\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'M:\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'M:\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'M:\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--sample_prompts=M:\\fluxgym\\outputs\\baoguo\\sample_prompts.txt', '--sample_every_n_steps=100', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'M:\\fluxgym\\outputs\\baoguo\\dataset.toml', '--output_dir', 'M:\\fluxgym\\outputs\\baoguo', '--output_name', 'baoguo', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-09-29 06:45:29] [ERROR] Command exited with code 1
[2024-09-29 06:45:29] [INFO] Runner: <LogsViewRunner nb_logs=255 exit_code=1>
![QQ20240926-033407](https://github.com/user-attachments/assets/ab6afd43-a3cf-483b-8510-b59cc3f8336c)

**Comment by sunyiwk** [comment]
![微信图片_20240929153946](https://github.com/user-attachments/assets/272e6e74-57d6-42fc-bc9f-851af3fad112)

**Comment by KeeeeperOfTheLight** [comment]
same here

**Comment by NemukaPrime** [comment]
Same issue after doing `git pull https://github.com/cocktailpeanut/fluxgym`

**Comment by kksinsa** [comment]
same here
