### ISSUE TITLE
ModuleNotFoundError: No module named 'voluptuous'

### ISSUE THREAD

**Issue by Vektor369** [cocktailpeanut/fluxgym#150]
```
Microsoft Windows [Version 10.0.19045.4894]
(c) Microsoft Corporation. All rights reserved.

F:\AI\FluxGym>python -m venv env

F:\AI\FluxGym>env\Scripts\activate

(env) F:\AI\FluxGym>python app.py
Traceback (most recent call last):
  File "F:\AI\FluxGym\app.py", line 21, in <module>
    import train_network
  File "F:\AI\FluxGym\sd-scripts\train_network.py", line 26, in <module>
    import library.config_util as config_util
  File "F:\AI\FluxGym\sd-scripts\library\config_util.py", line 22, in <module>
    import voluptuous
ModuleNotFoundError: No module named 'voluptuous'

(env) F:\AI\FluxGym>
```

**Comment by jcflorville** [comment]
Same error... Any ideas?!

**Comment by iwoolf** [comment]
I had the same error on Ubuntu. Not method of installing voluptuous got rid of the error. I'm now trying a pinokio install and getting different errors.

**Comment by chenziyi2018** [comment]
same in ubuntu server.  user root . so, anyone fix it?

**Comment by heiyu8** [comment]
pip uninstall diffusers

pip cache purge

pip install diffusers

**Comment by andapka** [comment]
I fixed it in that way:
1. Open the directory where pinokio was installed (e.g. by default "/Users/<username>/pinokio")
2. cd api/fluxgym
3. source env/bin/activate
4. pip install voluptuous
5. Run again in the pinokio app
