### ISSUE TITLE
[ERROR] Command exited with code 1

### ISSUE THREAD

**Issue by sunyiwk** [cocktailpeanut/fluxgym#153]
[2024-09-30 22:20:25] [INFO] Running bash "/gemini/code/fluxgym/outputs/gouba/train.sh"
[2024-09-30 22:21:30] [INFO] The following values were not passed to `accelerate launch` and had defaults used instead:
[2024-09-30 22:21:30] [INFO] `--num_processes` was set to a value of `2`
[2024-09-30 22:21:30] [INFO] More than one GPU was found, enabling multi-GPU training.
[2024-09-30 22:21:30] [INFO] If this was unintended please pass in `--num_processes=1`.
[2024-09-30 22:21:30] [INFO] `--num_machines` was set to a value of `1`
[2024-09-30 22:21:30] [INFO] `--dynamo_backend` was set to a value of `'no'`
[2024-09-30 22:21:30] [INFO] To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-09-30 22:21:30] [INFO] Using config file: /etc/orion/env/env.conf
[2024-09-30 22:22:40] [INFO] highvram is enabled / highvramが有効です
[2024-09-30 22:22:40] [INFO] highvram is enabled / highvramが有効です
[2024-09-30 22:22:40] [INFO] 2024-09-30 22:22:40 WARNING  cache_latents_to_disk is enabled, so cache_latents is also enabled /          train_util.py:4022
[2024-09-30 22:22:40] [INFO] cache_latents_to_diskが有効なため、cache_latentsを有効にします
[2024-09-30 22:22:40] [INFO] 2024-09-30 22:22:40 WARNING  cache_latents_to_disk is enabled, so cache_latents is also enabled /          train_util.py:4022
[2024-09-30 22:22:40] [INFO] cache_latents_to_diskが有効なため、cache_latentsを有効にします
[2024-09-30 22:22:41] [INFO] 2024-09-30 22:22:41 INFO     t5xxl_max_token_length: 512                                            flux_train_network.py:155
[2024-09-30 22:22:41] [INFO] 2024-09-30 22:22:41 INFO     t5xxl_max_token_length: 512                                            flux_train_network.py:155
[2024-09-30 22:23:41] [INFO] Traceback (most recent call last):
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/flux_train_network.py", line 522, in <module>
[2024-09-30 22:23:41] [INFO] trainer.train(args)
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/train_network.py", line 268, in train
[2024-09-30 22:23:41] [INFO] tokenize_strategy = self.get_tokenize_strategy(args)
[2024-09-30 22:23:41] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/flux_train_network.py", line 156, in get_tokenize_strategy
[2024-09-30 22:23:41] [INFO] return strategy_flux.FluxTokenizeStrategy(t5xxl_max_token_length, args.tokenizer_cache_dir)
[2024-09-30 22:23:41] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/library/strategy_flux.py", line 26, in __init__
[2024-09-30 22:23:41] [INFO] self.clip_l = self._load_tokenizer(CLIPTokenizer, CLIP_L_TOKENIZER_ID, tokenizer_cache_dir=tokenizer_cache_dir)
[2024-09-30 22:23:41] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/library/strategy_base.py", line 46, in _load_tokenizer
[2024-09-30 22:23:41] [INFO] Traceback (most recent call last):
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/flux_train_network.py", line 522, in <module>
[2024-09-30 22:23:41] [INFO] trainer.train(args)
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/train_network.py", line 268, in train
[2024-09-30 22:23:41] [INFO] tokenize_strategy = self.get_tokenize_strategy(args)
[2024-09-30 22:23:41] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/flux_train_network.py", line 156, in get_tokenize_strategy
[2024-09-30 22:23:41] [INFO] return strategy_flux.FluxTokenizeStrategy(t5xxl_max_token_length, args.tokenizer_cache_dir)
[2024-09-30 22:23:41] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/library/strategy_flux.py", line 26, in __init__
[2024-09-30 22:23:41] [INFO] tokenizer = model_class.from_pretrained(model_id, subfolder=subfolder)
[2024-09-30 22:23:41] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/env/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2255, in from_pretrained
[2024-09-30 22:23:41] [INFO] self.clip_l = self._load_tokenizer(CLIPTokenizer, CLIP_L_TOKENIZER_ID, tokenizer_cache_dir=tokenizer_cache_dir)
[2024-09-30 22:23:41] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/sd-scripts/library/strategy_base.py", line 46, in _load_tokenizer
[2024-09-30 22:23:41] [INFO] raise EnvironmentError(
[2024-09-30 22:23:41] [INFO] OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
[2024-09-30 22:23:41] [INFO] tokenizer = model_class.from_pretrained(model_id, subfolder=subfolder)
[2024-09-30 22:23:41] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:41] [INFO] File "/gemini/code/fluxgym/env/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2255, in from_pretrained
[2024-09-30 22:23:41] [INFO] raise EnvironmentError(
[2024-09-30 22:23:41] [INFO] OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
[2024-09-30 22:23:44] [INFO] E0930 22:23:44.203000 140346803736960 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 472) of binary: /gemini/code/fluxgym/env/bin/python
[2024-09-30 22:23:44] [INFO] Traceback (most recent call last):
[2024-09-30 22:23:44] [INFO] File "/gemini/code/fluxgym/env/bin/accelerate", line 8, in <module>
[2024-09-30 22:23:44] [INFO] sys.exit(main())
[2024-09-30 22:23:44] [INFO] ^^^^^^
[2024-09-30 22:23:44] [INFO] File "/gemini/code/fluxgym/env/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
[2024-09-30 22:23:44] [INFO] args.func(args)
[2024-09-30 22:23:44] [INFO] File "/gemini/code/fluxgym/env/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
[2024-09-30 22:23:44] [INFO] multi_gpu_launcher(args)
[2024-09-30 22:23:44] [INFO] File "/gemini/code/fluxgym/env/lib/python3.11/site-packages/accelerate/commands/launch.py", line 734, in multi_gpu_launcher
[2024-09-30 22:23:44] [INFO] distrib_run.run(args)
[2024-09-30 22:23:44] [INFO] File "/gemini/code/fluxgym/env/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
[2024-09-30 22:23:44] [INFO] elastic_launch(
[2024-09-30 22:23:44] [INFO] File "/gemini/code/fluxgym/env/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
[2024-09-30 22:23:44] [INFO] return launch_agent(self._config, self._entrypoint, list(args))
[2024-09-30 22:23:44] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-30 22:23:44] [INFO] File "/gemini/code/fluxgym/env/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
[2024-09-30 22:23:44] [INFO] raise ChildFailedError(
[2024-09-30 22:23:44] [INFO] torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
[2024-09-30 22:23:44] [INFO] ============================================================
[2024-09-30 22:23:44] [INFO] sd-scripts/flux_train_network.py FAILED
[2024-09-30 22:23:44] [INFO] ------------------------------------------------------------
[2024-09-30 22:23:44] [INFO] Failures:
[2024-09-30 22:23:44] [INFO] [1]:
[2024-09-30 22:23:44] [INFO] time      : 2024-09-30_22:23:44
[2024-09-30 22:23:44] [INFO] host      : gjob-dev-495959626316238848-taskrole1-0
[2024-09-30 22:23:44] [INFO] rank      : 1 (local_rank: 1)
[2024-09-30 22:23:44] [INFO] exitcode  : 1 (pid: 473)
[2024-09-30 22:23:44] [INFO] error_file: <N/A>
[2024-09-30 22:23:44] [INFO] traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2024-09-30 22:23:44] [INFO] ------------------------------------------------------------
[2024-09-30 22:23:44] [INFO] Root Cause (first observed failure):
[2024-09-30 22:23:44] [INFO] [0]:
[2024-09-30 22:23:44] [INFO] time      : 2024-09-30_22:23:44
[2024-09-30 22:23:44] [INFO] host      : gjob-dev-495959626316238848-taskrole1-0
[2024-09-30 22:23:44] [INFO] rank      : 0 (local_rank: 0)
[2024-09-30 22:23:44] [INFO] exitcode  : 1 (pid: 472)
[2024-09-30 22:23:44] [INFO] error_file: <N/A>
[2024-09-30 22:23:44] [INFO] traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2024-09-30 22:23:44] [INFO] ============================================================
[2024-09-30 22:23:44] [ERROR] Command exited with code 1
[2024-09-30 22:23:44] [INFO] Runner: <LogsViewRunner nb_logs=94 exit_code=1>

**Comment by kksinsa** [comment]
same here

**Comment by ShirleyyyChen** [comment]
same here

**Comment by bozagina** [comment]
have you figured it out? I think you need to download these models to local directory first
