### ISSUE TITLE
Terminating process <Popen: returncode: None args: ['bash "/app/fluxgym/outputs/test-model/train...>

### ISSUE THREAD

**Issue by fahadshery** [cocktailpeanut/fluxgym#166]
Hi,

even though I dockerised it, but didn't have the time to train any model 🗡️ 
so I uploaded a character's mixed photos and clicked Train after captions etc.
I can confirm that it created the `output/test-model` directory with images and captions and a `shell script` with the following:

```
accelerate launch \
  --mixed_precision bf16 \
  --num_cpu_threads_per_process 1 \
  sd-scripts/flux_train_network.py \
  --pretrained_model_name_or_path "/app/fluxgym/models/unet/flux1-dev.sft" \
  --clip_l "/app/fluxgym/models/clip/clip_l.safetensors" \
  --t5xxl "/app/fluxgym/models/clip/t5xxl_fp16.safetensors" \
  --ae "/app/fluxgym/models/vae/ae.sft" \
  --cache_latents_to_disk \
  --save_model_as safetensors \
  --sdpa --persistent_data_loader_workers \
  --max_data_loader_n_workers 2 \
  --seed 42 \
  --gradient_checkpointing \
  --mixed_precision bf16 \
  --save_precision bf16 \
  --network_module networks.lora_flux \
  --network_dim 4 \
  --optimizer_type adamw8bit \
  --learning_rate 8e-4 \
  --cache_text_encoder_outputs \
  --cache_text_encoder_outputs_to_disk \
  --fp8_base \
  --highvram \
  --max_train_epochs 12 \
  --save_every_n_epochs 4 \
  --dataset_config "/app/fluxgym/outputs/test-model/dataset.toml" \
  --output_dir "/app/fluxgym/outputs/test-model" \
  --output_name test-model \
  --timestep_sampling shift \
  --discrete_flow_shift 3.1582 \
  --model_prediction_type raw \
  --guidance_scale 1 \
  --loss_type l2 \
```

notice the last line have `\` at the end. Is it causing it to fail?

Here are the logs:
```
destination_folder datasets/test-model
download flux-dev
flux1-dev.sft: 100% 23.8G/23.8G [1:03:49<00:00, 6.22MB/s]
downloading ae.sft...
ae.sft: 100% 335M/335M [00:57<00:00, 5.80MB/s]
Terminating process <Popen: returncode: None args: ['bash "/app/fluxgym/outputs/test-model/train...>
Killing process: <Popen: returncode: None args: ['bash "/app/fluxgym/outputs/test-model/train...>
```

Additionally, I already copied `flux dev` and other files in the folders but they had `safetensors` extension instead of `.sft` so it started downloaded the models again. I would suggest if we could look for `.safetensors` files as well before downloading?

**Comment by fahadshery** [comment]
so I deleted the leading `\` and then ran the `train.sh` and getting the following:
```
bash train.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/bin/python3: can't open file '/app/fluxgym/outputs/test-model/sd-scripts/flux_train_network.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', '/app/fluxgym/models/unet/flux1-dev.sft', '--clip_l', '/app/fluxgym/models/clip/clip_l.safetensors', '--t5xxl', '/app/fluxgym/models/clip/t5xxl_fp16.safetensors', '--ae', '/app/fluxgym/models/vae/ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adamw8bit', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '12', '--save_every_n_epochs', '4', '--dataset_config', '/app/fluxgym/outputs/test-model/dataset.toml', '--output_dir', '/app/fluxgym/outputs/test-model', '--output_name', 'test-model', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 2.
```

It is looking for `/sd-scripts/flux_train_network.py` in the `/app/fluxgym/outputs/test-model/sd-scripts/` directory but that should be in the main `/app/fluxgym/sd-scripts` directory.

**Comment by fahadshery** [comment]
ok, I rebuilt it using Docker and it seems to be working. Closing this issue now. thanks
