### ISSUE TITLE
Dataset Creation is not working correctly

### ISSUE THREAD

**Issue by alcool91** [cocktailpeanut/fluxgym#185]
Hello,

I have a folder of 100 pairs of jpg and txt files. 

1. I enter the name of the Lora and the trigger word 
2. Switch to medium vram (using a 3090), 
3. Drag in my dataset files (200 of them)
    - These all display perfectly in the ui
 4. Select Start Training
`Traceback (most recent call last):
  File "D:\fluxgym\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\fluxgym\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\fluxgym\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\fluxgym\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\fluxgym\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\fluxgym\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "D:\fluxgym\env\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "D:\fluxgym\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\fluxgym\app.py", line 248, in create_dataset
    original_caption = inputs[index + 1]
IndexError: tuple index out of range`

And when I go to inspect the dataset folder all 100 caption files are in there but just some of the images are in there.

**Comment by MegaCocos** [comment]
The same error here. FLUXGym only takes 76 images from 120 of the dataset with the same error of "tuple index out of range". If anybody knows the solution, please, help

**Comment by MegaCocos** [comment]
Solved with this https://github.com/cocktailpeanut/fluxgym/issues/22#issuecomment-2340331960
