### ISSUE TITLE
OSError: Can't load tokenizer for 'google/t5-v1_1-xxl'

### ISSUE THREAD

**Issue by hydra-bu** [cocktailpeanut/fluxgym#186]
```
[2024-10-12 10:10:56] [INFO] Running bash "/app/fluxgym/outputs/chinese-girl/train.sh"
[2024-10-12 10:10:58] [INFO] /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:654: UserWarning: Can't initialize NVML
[2024-10-12 10:10:58] [INFO] warnings.warn("Can't initialize NVML")
[2024-10-12 10:10:58] [INFO] The following values were not passed to `accelerate launch` and had defaults used instead:
[2024-10-12 10:10:58] [INFO] `--num_processes` was set to a value of `0`
[2024-10-12 10:10:58] [INFO] `--num_machines` was set to a value of `1`
[2024-10-12 10:10:58] [INFO] `--dynamo_backend` was set to a value of `'no'`
[2024-10-12 10:10:58] [INFO] To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-10-12 10:11:00] [INFO] /usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
[2024-10-12 10:11:00] [INFO] torch.utils._pytree._register_pytree_node(
[2024-10-12 10:11:00] [INFO] /usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
[2024-10-12 10:11:00] [INFO] torch.utils._pytree._register_pytree_node(
[2024-10-12 10:11:00] [INFO] highvram is enabled / highvramが有効です
[2024-10-12 10:11:00] [INFO] 2024-10-12 10:11:00 WARNING  cache_latents_to_disk is         train_util.py:4054
[2024-10-12 10:11:00] [INFO] enabled, so cache_latents is
[2024-10-12 10:11:00] [INFO] also enabled /
[2024-10-12 10:11:00] [INFO] cache_latents_to_diskが有効なた
[2024-10-12 10:11:00] [INFO] め、cache_latentsを有効にします
[2024-10-12 10:11:00] [INFO] 2024-10-12 10:11:00 INFO     Checking the state dict: Diffusers flux_utils.py:48
[2024-10-12 10:11:00] [INFO] or BFL, dev or schnell
[2024-10-12 10:11:00] [INFO] INFO     t5xxl_max_token_length:   flux_train_network.py:152
[2024-10-12 10:11:00] [INFO] 512
[2024-10-12 10:11:01] [INFO] /usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
[2024-10-12 10:11:01] [INFO] warnings.warn(
[2024-10-12 10:12:01] [INFO] Traceback (most recent call last):
[2024-10-12 10:12:01] [INFO] File "/app/fluxgym/sd-scripts/flux_train_network.py", line 519, in <module>
[2024-10-12 10:12:01] [INFO] trainer.train(args)
[2024-10-12 10:12:01] [INFO] File "/app/fluxgym/sd-scripts/train_network.py", line 268, in train
[2024-10-12 10:12:01] [INFO] tokenize_strategy = self.get_tokenize_strategy(args)
[2024-10-12 10:12:01] [INFO] File "/app/fluxgym/sd-scripts/flux_train_network.py", line 153, in get_tokenize_strategy
[2024-10-12 10:12:01] [INFO] return strategy_flux.FluxTokenizeStrategy(t5xxl_max_token_length, args.tokenizer_cache_dir)
[2024-10-12 10:12:01] [INFO] File "/app/fluxgym/sd-scripts/library/strategy_flux.py", line 27, in __init__
[2024-10-12 10:12:01] [INFO] self.t5xxl = self._load_tokenizer(T5TokenizerFast, T5_XXL_TOKENIZER_ID, tokenizer_cache_dir=tokenizer_cache_dir)
[2024-10-12 10:12:01] [INFO] File "/app/fluxgym/sd-scripts/library/strategy_base.py", line 65, in _load_tokenizer
[2024-10-12 10:12:01] [INFO] tokenizer = model_class.from_pretrained(model_id, subfolder=subfolder)
[2024-10-12 10:12:01] [INFO] File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2255, in from_pretrained
[2024-10-12 10:12:01] [INFO] raise EnvironmentError(
[2024-10-12 10:12:01] [INFO] OSError: Can't load tokenizer for 'google/t5-v1_1-xxl'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'google/t5-v1_1-xxl' is the correct path to a directory containing all relevant files for a T5TokenizerFast tokenizer.
[2024-10-12 10:12:01] [INFO] Traceback (most recent call last):
[2024-10-12 10:12:01] [INFO] File "/usr/local/bin/accelerate", line 8, in <module>
[2024-10-12 10:12:01] [INFO] sys.exit(main())
[2024-10-12 10:12:01] [INFO] File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
[2024-10-12 10:12:01] [INFO] args.func(args)
[2024-10-12 10:12:01] [INFO] File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1106, in launch_command
[2024-10-12 10:12:01] [INFO] simple_launcher(args)
[2024-10-12 10:12:01] [INFO] File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 704, in simple_launcher
[2024-10-12 10:12:01] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-10-12 10:12:01] [INFO] subprocess.CalledProcessError: Command '['/usr/bin/python3', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', '/app/fluxgym/models/unet/flux1-dev.sft', '--clip_l', '/app/fluxgym/models/clip/clip_l.safetensors', '--t5xxl', '/app/fluxgym/models/clip/t5xxl_fp16.safetensors', '--ae', '/app/fluxgym/models/vae/ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--sample_prompts=/app/fluxgym/outputs/chinese-girl/sample_prompts.txt', '--sample_every_n_steps=100', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', '/app/fluxgym/outputs/chinese-girl/dataset.toml', '--output_dir', '/app/fluxgym/outputs/chinese-girl', '--output_name', 'chinese-girl', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-10-12 10:12:01] [ERROR] Command exited with code 1
[2024-10-12 10:12:01] [INFO] Runner: <LogsViewRunner nb_logs=49 exit_code=1>
```

**Comment by hydra-bu** [comment]
The issue has been resolved; it wasn't due to network connectivity. I was using Docker for deployment, but switching to direct deployment on the host machine fixed the problem.
