### ISSUE TITLE
Code doesn't run with No Samples error - related to Error: libnvrtc.so.12 ?

### ISSUE THREAD

**Issue by shaun-ba** [cocktailpeanut/fluxgym#208]
Running on Linux, installed as per instructions and setup as per instructions.

Ran with "Sample Image Every N Steps" set to 64, and received this error (yes I used prompts). Also ran with it set to 0 and still received it.

Just before the trackback it references the Error: libnvrtc.so.12 ? so is it related?

```
[2024-10-21 09:13:01] [INFO] INFO     caching Text Encoder outputs...                                                train_util.py:1269
[2024-10-21 09:13:01] [INFO] 0%|          | 0/34 [00:00<?, ?it/s]Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
[2024-10-21 09:13:01] [INFO] Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
[2024-10-21 09:13:01] [INFO] Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
[2024-10-21 09:13:01] [INFO] Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
[2024-10-21 09:13:01] [INFO] Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
[2024-10-21 09:13:01] [INFO] Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
[2024-10-21 09:13:01] [INFO] 0%|          | 0/34 [00:00<?, ?it/s]
[2024-10-21 09:13:01] [INFO] Traceback (most recent call last):
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/sd-scripts/flux_train_network.py", line 564, in <module>
[2024-10-21 09:13:01] [INFO] trainer.train(args)
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/sd-scripts/train_network.py", line 426, in train
[2024-10-21 09:13:01] [INFO] self.cache_text_encoder_outputs_if_needed(args, accelerator, unet, vae, text_encoders, train_dataset_group, weight_dtype)
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/sd-scripts/flux_train_network.py", line 225, in cache_text_encoder_outputs_if_needed
[2024-10-21 09:13:01] [INFO] dataset.new_cache_text_encoder_outputs(text_encoders, accelerator)
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/sd-scripts/library/train_util.py", line 2503, in new_cache_text_encoder_outputs
[2024-10-21 09:13:01] [INFO] dataset.new_cache_text_encoder_outputs(models, accelerator)
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/sd-scripts/library/train_util.py", line 1272, in new_cache_text_encoder_outputs
[2024-10-21 09:13:01] [INFO] caching_strategy.cache_batch_outputs(tokenize_strategy, models, text_encoding_strategy, batch)
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/sd-scripts/library/strategy_flux.py", line 162, in cache_batch_outputs
[2024-10-21 09:13:01] [INFO] l_pooled, t5_out, txt_ids, _ = flux_text_encoding_strategy.encode_tokens(tokenize_strategy, models, tokens_and_masks)
[2024-10-21 09:13:01] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/sd-scripts/library/strategy_flux.py", line 68, in encode_tokens
[2024-10-21 09:13:01] [INFO] l_pooled = clip_l(l_tokens.to(clip_l.device))["pooler_output"]
[2024-10-21 09:13:01] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[2024-10-21 09:13:01] [INFO] return self._call_impl(*args, **kwargs)
[2024-10-21 09:13:01] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-21 09:13:01] [INFO] File "/training/fluxgym/env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[2024-10-21 09:13:01] [INFO] return forward_call(*args, **kwargs)
[2024-10-21 09:13:01] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by HorusPi** [comment]
The exact same problem with docker installation with the docker-compose for cuda 12

[2024-10-26 12:00:35] [INFO] 0%|          | 0/22 [00:00<?, ?it/s]Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
[2024-10-26 12:00:35] [INFO] Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
[2024-10-26 12:00:35] [INFO] Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
[2024-10-26 12:00:35] [INFO] Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
[2024-10-26 12:00:35] [INFO] Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
[2024-10-26 12:00:35] [INFO] Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory
[2024-10-26 12:00:35] [INFO] 0%|          | 0/22 [00:00<?, ?it/s]
[2024-10-26 12:00:35] [INFO] Traceback (most recent call last):
[2024-10-26 12:00:35] [INFO] File "/app/fluxgym/sd-scripts/flux_train_network.py", line 519, in <module>
[2024-10-26 12:00:35] [INFO] trainer.train(args)
[2024-10-26 12:00:35] [INFO] File "/app/fluxgym/sd-scripts/train_network.py", line 402, in train
[2024-10-26 12:00:35] [INFO] self.cache_text_encoder_outputs_if_needed(args, accelerator, unet, vae, text_encoders, train_dataset_group, weight_dtype)
[2024-10-26 12:00:35] [INFO] File "/app/fluxgym/sd-scripts/flux_train_network.py", line 225, in cache_text_encoder_outputs_if_needed
[2024-10-26 12:00:35] [INFO] dataset.new_cache_text_encoder_outputs(text_encoders, accelerator)
[2024-10-26 12:00:35] [INFO] File "/app/fluxgym/sd-scripts/library/train_util.py", line 2489, in new_cache_text_encoder_outputs
[2024-10-26 12:00:35] [INFO] dataset.new_cache_text_encoder_outputs(models, accelerator)
[2024-10-26 12:00:35] [INFO] File "/app/fluxgym/sd-scripts/library/train_util.py", line 1263, in new_cache_text_encoder_outputs
[2024-10-26 12:00:35] [INFO] caching_strategy.cache_batch_outputs(tokenize_strategy, models, text_encoding_strategy, batch)
[2024-10-26 12:00:35] [INFO] File "/app/fluxgym/sd-scripts/library/strategy_flux.py", line 162, in cache_batch_outputs
[2024-10-26 12:00:35] [INFO] l_pooled, t5_out, txt_ids, _ = flux_text_encoding_strategy.encode_tokens(tokenize_strategy, models, tokens_and_masks)
[2024-10-26 12:00:35] [INFO] File "/app/fluxgym/sd-scripts/library/strategy_flux.py", line 68, in encode_tokens
[2024-10-26 12:00:35] [INFO] l_pooled = clip_l(l_tokens.to(clip_l.device))["pooler_output"]
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[2024-10-26 12:00:35] [INFO] return self._call_impl(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[2024-10-26 12:00:35] [INFO] return forward_call(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 986, in forward
[2024-10-26 12:00:35] [INFO] return self.text_model(
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[2024-10-26 12:00:35] [INFO] return self._call_impl(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[2024-10-26 12:00:35] [INFO] return forward_call(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 890, in forward
[2024-10-26 12:00:35] [INFO] encoder_outputs = self.encoder(
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[2024-10-26 12:00:35] [INFO] return self._call_impl(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[2024-10-26 12:00:35] [INFO] return forward_call(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 813, in forward
[2024-10-26 12:00:35] [INFO] layer_outputs = encoder_layer(
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[2024-10-26 12:00:35] [INFO] return self._call_impl(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[2024-10-26 12:00:35] [INFO] return forward_call(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 548, in forward
[2024-10-26 12:00:35] [INFO] hidden_states, attn_weights = self.self_attn(
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[2024-10-26 12:00:35] [INFO] return self._call_impl(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[2024-10-26 12:00:35] [INFO] return forward_call(*args, **kwargs)
[2024-10-26 12:00:35] [INFO] File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 480, in forward
[2024-10-26 12:00:35] [INFO] attn_output = torch.nn.functional.scaled_dot_product_attention(
[2024-10-26 12:00:35] [INFO] RuntimeError: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.
[2024-10-26 12:00:36] [INFO] Traceback (most recent call last):
[2024-10-26 12:00:36] [INFO] File "/usr/local/bin/accelerate", line 8, in <module>
[2024-10-26 12:00:36] [INFO] sys.exit(main())
[2024-10-26 12:00:36] [INFO] File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
[2024-10-26 12:00:36] [INFO] args.func(args)
[2024-10-26 12:00:36] [INFO] File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1106, in launch_command
[2024-10-26 12:00:36] [INFO] simple_launcher(args)
[2024-10-26 12:00:36] [INFO] File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 704, in simple_launcher
[2024-10-26 12:00:36] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-10-26 12:00:36] [INFO] subprocess.CalledProcessError: Command '['/usr/bin/python3', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', '/app/fluxgym/models/unet/flux1-dev.sft', '--clip_l', '/app/fluxgym/models/clip/clip_l.safetensors', '--t5xxl', '/app/fluxgym/models/clip/t5xxl_fp16.safetensors', '--ae', '/app/fluxgym/models/vae/ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--sample_prompts=/app/fluxgym/outputs/TESTc1/sample_prompts.txt', '--sample_every_n_steps=176', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '10', '--save_every_n_epochs', '4', '--dataset_config', '/app/fluxgym/outputs/TESTc1/dataset.toml', '--output_dir', '/app/fluxgym/outputs/TESTc1', '--output_name', 'TESTc1', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-10-26 12:00:37] [ERROR] Command exited with code 1
[2024-10-26 12:00:37] [INFO] Runner: <LogsViewRunner nb_logs=188 exit_code=1>

**Comment by PeteSmalls** [comment]
Running Windows, manual install- same thing.
I must be the only one.. I keep checking here and reddit --No updates
------So my work around for the last months-------
I setup a clean conda env, do a clean install of FluxGym, move the model folder over and I get 1 good run.
It is amazing when it works.
Come back the next day and I get this "no samples" error around line 70...
I wipe the env
I setup a clean conda env, do a clean install of FluxGym, move the model folder over and I get 1 good run.
It is amazing when it works.
Come back the next day and I get this "no samples" error around line 70...
I wipe the env
I setup a clean conda env, do a clean install of FluxGym, move the model folder over and I get 1 good run.
...........
Good times.

**Comment by catowabisabi** [comment]
Read the error msg. Try to covert your txt files to utf-8 can fix your problem. Most likely u tried to change the auto gen caption and u typed some non special character. Or using a non utf8 input method.

You can use a pyhton to check all the txt and remove the chars and save as utf8. It should got fix
