### ISSUE TITLE
option for 8 vram

### ISSUE THREAD

**Issue by jonnytracker** [cocktailpeanut/fluxgym#216]
option for 8 vram with smaller checkpoints

**Comment by jonnytracker** [comment]
No it crash and exit

**Comment by Von-D-Aifvan** [comment]
> Just select 12GB, it worked fine on my 8GB 4060 to train a lora

What configuration did you use and how was your sample? I always get Cuda OOM 

[2024-12-02 18:58:40] [INFO] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 80.00 MiB. GPU 0 has a total capacity of 7.75 GiB of which 57.62 MiB is free. Including non-PyTorch memory, this process has 7.68 GiB memory in use. Of the allocated memory 7.51 GiB is allocated by PyTorch, and 14.35 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-12-02 18:58:42] [INFO] Traceback (most recent call last):
[2024-12-02 18:58:42] [INFO] File "/home/vonan/fluxgym/env/bin/accelerate", line 8, in <module>
[2024-12-02 18:58:42] [INFO] sys.exit(main())

**Comment by hangry-goblin** [comment]
I'm having the same error trying to train on a small dataset

Traceback (most recent call last):
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\flux_train_network.py", line 583, in
[2024-12-22 21:17:59] [INFO] trainer.train(args)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\train_network.py", line 1222, in train
[2024-12-22 21:17:59] [INFO] noise_pred, target, timesteps, weighting = self.get_noise_pred_and_target(
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\flux_train_network.py", line 428, in get_noise_pred_and_target
[2024-12-22 21:17:59] [INFO] model_pred = call_dit(
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\flux_train_network.py", line 380, in call_dit
[2024-12-22 21:17:59] [INFO] model_pred = unet(
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
[2024-12-22 21:17:59] [INFO] return self._call_impl(*args, **kwargs)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
[2024-12-22 21:17:59] [INFO] return forward_call(*args, **kwargs)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\utils\operations.py", line 819, in forward
[2024-12-22 21:17:59] [INFO] return model_forward(*args, **kwargs)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\utils\operations.py", line 807, in call
[2024-12-22 21:17:59] [INFO] return convert_to_fp32(self.model_forward(*args, **kwargs))
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\amp\autocast_mode.py", line 44, in decorate_autocast
[2024-12-22 21:17:59] [INFO] return func(*args, **kwargs)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\library\flux_models.py", line 1055, in forward
[2024-12-22 21:17:59] [INFO] self.offloader_double.wait_for_block(block_idx)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\library\custom_offloading_utils.py", line 218, in wait_for_block
[2024-12-22 21:17:59] [INFO] self._wait_blocks_move(block_idx)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\library\custom_offloading_utils.py", line 143, in _wait_blocks_move
[2024-12-22 21:17:59] [INFO] _, bidx_to_cuda = future.result()
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\bin\miniconda\lib\concurrent\futures_base.py", line 451, in result
[2024-12-22 21:17:59] [INFO] return self.__get_result()
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\bin\miniconda\lib\concurrent\futures_base.py", line 403, in __get_result
[2024-12-22 21:17:59] [INFO] raise self._exception
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\bin\miniconda\lib\concurrent\futures\thread.py", line 58, in run
[2024-12-22 21:17:59] [INFO] result = self.fn(*self.args, **self.kwargs)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\library\custom_offloading_utils.py", line 121, in move_blocks
[2024-12-22 21:17:59] [INFO] self.swap_weight_devices(block_to_cpu, block_to_cuda)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\library\custom_offloading_utils.py", line 111, in swap_weight_devices
[2024-12-22 21:17:59] [INFO] swap_weight_devices_cuda(self.device, block_to_cpu, block_to_cuda)
[2024-12-22 21:17:59] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\library\custom_offloading_utils.py", line 50, in swap_weight_devices_cuda
[2024-12-22 21:17:59] [INFO] module_to_cpu.weight.data = cuda_data_view.data.to("cpu", non_blocking=True)
[2024-12-22 21:17:59] [INFO] RuntimeError: CUDA error: out of memory
[2024-12-22 21:17:59] [INFO] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[2024-12-22 21:17:59] [INFO] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[2024-12-22 21:17:59] [INFO] Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
[2024-12-22 21:17:59] [INFO]
[2024-12-22 21:17:59] [INFO] steps: 0%| | 0/288 [00:28<?, ?it/s]

Training command:
accelerate launch ^
--mixed_precision bf16 ^
--num_cpu_threads_per_process 1 ^
sd-scripts/flux_train_network.py ^
--pretrained_model_name_or_path "C:\pinokio\api\fluxgym.git\models\unet\flux1-dev.sft" ^
--clip_l "C:\pinokio\api\fluxgym.git\models\clip\clip_l.safetensors" ^
--t5xxl "C:\pinokio\api\fluxgym.git\models\clip\t5xxl_fp16.safetensors" ^
--ae "C:\pinokio\api\fluxgym.git\models\vae\ae.sft" ^
--cache_latents_to_disk ^
--save_model_as safetensors ^
--sdpa --persistent_data_loader_workers ^
--max_data_loader_n_workers 2 ^
--seed 42 ^
--gradient_checkpointing ^
--mixed_precision bf16 ^
--save_precision bf16 ^
--network_module networks.lora_flux ^
--network_dim 4 ^
--optimizer_type adafactor ^
--optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False" ^
--split_mode ^
--network_args "train_blocks=single" ^
--lr_scheduler constant_with_warmup ^
--max_grad_norm 0.0 ^
--learning_rate 8e-4 ^
--cache_text_encoder_outputs ^
--cache_text_encoder_outputs_to_disk ^
--fp8_base ^
--highvram ^
--max_train_epochs 4 ^
--save_every_n_epochs 1 ^
--dataset_config "C:\pinokio\api\fluxgym.git\outputs\angel\dataset.toml" ^
--output_dir "C:\pinokio\api\fluxgym.git\outputs\angel" ^
--output_name angel ^
--timestep_sampling shift ^
--discrete_flow_shift 3.1582 ^
--model_prediction_type raw ^
--guidance_scale 1 ^
--loss_type l2 ^
--cache_latents

I initially tried with 24 images, 5 trains per image and 8 epochs for a total of 960 steps. When that failed I tried 12 images, 3 trains per image and 4 epochs for a total of 144 steps, but that also failed. Tried reducing captioning from Florence-2 generated to short handcrafted ones, then just the trigger word, but no luck. I've also tried enabling cache_latents and disabling the highvram option in code but it didn't work. I'm using a 3060ti with 8 GB VRAM and 16 GB RAM
