### ISSUE TITLE
Runner: <LogsViewRunner nb_logs=62 exit_code=1>

### ISSUE THREAD

**Issue by tiandaoyuxi** [cocktailpeanut/fluxgym#230]
[2024-11-01 09:14:31] [INFO] Traceback (most recent call last):
[2024-11-01 09:14:31] [INFO] File "<frozen runpy>", line 198, in _run_module_as_main
[2024-11-01 09:14:31] [INFO] File "<frozen runpy>", line 88, in _run_code
[2024-11-01 09:14:31] [INFO] File "C:\Users\win11\.conda\envs\fluxgym\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-11-01 09:14:31] [INFO] File "C:\Users\win11\.conda\envs\fluxgym\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-11-01 09:14:31] [INFO] args.func(args)
[2024-11-01 09:14:31] [INFO] File "C:\Users\win11\.conda\envs\fluxgym\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-11-01 09:14:31] [INFO] simple_launcher(args)
[2024-11-01 09:14:31] [INFO] File "C:\Users\win11\.conda\envs\fluxgym\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-11-01 09:14:31] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-11-01 09:14:31] [INFO] subprocess.CalledProcessError: Command '['C:\\Users\\win11\\.conda\\envs\\fluxgym\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'D:\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'D:\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'D:\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'D:\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adamw8bit', '--sample_prompts=D:\\fluxgym\\outputs\\lbttest\\sample_prompts.txt', '--sample_every_n_steps=2', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'D:\\fluxgym\\outputs\\lbttest\\dataset.toml', '--output_dir', 'D:\\fluxgym\\outputs\\lbttest', '--output_name', 'lbttest', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-11-01 09:14:31] [ERROR] Command exited with code 1
[2024-11-01 09:14:31] [INFO] Runner: <LogsViewRunner nb_logs=62 exit_code=1>

**Comment by Djanghost** [comment]
Same here, can't use fluxgym anymore

**Comment by AkiraToya** [comment]
So, is this unsolvable? I also got this error. I previously think my system can't handle it ( but no cuda oom etc ), just like above. Then I find one that can be used on google colab, also the same. Got this error.

**Comment by TijmenJansen0** [comment]
I had the same error after downloading and using the UI locally.
Bug can be fixed by running (in terminal/bash)
export PATH="/PATH_TO_YOUR_ENVIRONMENT/bin:$PATH"

before running
python app.py

**Comment by Yosh85** [comment]
> I had the same error after downloading and using the UI locally. Bug can be fixed by running (in terminal/bash) export PATH="/PATH_TO_YOUR_ENVIRONMENT/bin:$PATH"
> 
> before running python app.py

i don't understand, can u give more details please?

**Comment by TijmenJansen0** [comment]
The error occurred for me when downloading and running on Linux. 
The first time downloading, installing and running fluxgym in my Python environment worked fine but when trying to run it again, this error occurred. I could fix that by running
PATH="/PATH_TO_YOUR_ENVIRONMENT/bin:$PATH"

Running this command ensured the correct environment binaries were prioritized, resolving the issue. Only works when you have a dedicated environment where you run fluxgym.
