### ISSUE TITLE
Runner: <LogsViewRunner nb_logs=56 exit_code=1>

### ISSUE THREAD

**Issue by lesteryebin** [cocktailpeanut/fluxgym#231]
2024-11-01 17:58:06] [INFO] To avoid this warning pass in values for each of the problematic parameters or run accelerate config.
[2024-11-01 17:58:10] [INFO] 2024-11-01 17:58:10 INFO     highvram is enabled /           train_util.py:4106
[2024-11-01 17:58:10] [INFO] highvramが有効です
[2024-11-01 17:58:10] [INFO] WARNING  cache_latents_to_disk is        train_util.py:4123
[2024-11-01 17:58:10] [INFO] enabled, so cache_latents is
[2024-11-01 17:58:10] [INFO] also enabled /
[2024-11-01 17:58:10] [INFO] cache_latents_to_diskが有効なた
[2024-11-01 17:58:10] [INFO] め、cache_latentsを有効にします
[2024-11-01 17:58:10] [INFO] 2024-11-01 17:58:10 INFO     Checking the state dict:          flux_utils.py:62
[2024-11-01 17:58:10] [INFO] Diffusers or BFL, dev or schnell
[2024-11-01 17:58:10] [INFO] INFO     t5xxl_max_token_length:  flux_train_network.py:152
[2024-11-01 17:58:10] [INFO] 512
[2024-11-01 17:58:10] [INFO] Traceback (most recent call last):
[2024-11-01 17:58:10] [INFO] File "E:\fluxgym\sd-scripts\flux_train_network.py", line 564, in <module>
[2024-11-01 17:58:10] [INFO] trainer.train(args)
[2024-11-01 17:58:10] [INFO] File "E:\fluxgym\sd-scripts\train_network.py", line 292, in train
[2024-11-01 17:58:10] [INFO] tokenize_strategy = self.get_tokenize_strategy(args)
[2024-11-01 17:58:10] [INFO] File "E:\fluxgym\sd-scripts\flux_train_network.py", line 153, in get_tokenize_strategy
[2024-11-01 17:58:10] [INFO] return strategy_flux.FluxTokenizeStrategy(t5xxl_max_token_length, args.tokenizer_cache_dir)
[2024-11-01 17:58:10] [INFO] File "E:\fluxgym\sd-scripts\library\strategy_flux.py", line 26, in __init__
[2024-11-01 17:58:10] [INFO] self.clip_l = self._load_tokenizer(CLIPTokenizer, CLIP_L_TOKENIZER_ID, tokenizer_cache_dir=tokenizer_cache_dir)
[2024-11-01 17:58:10] [INFO] File "E:\fluxgym\sd-scripts\library\strategy_base.py", line 65, in _load_tokenizer
[2024-11-01 17:58:10] [INFO] tokenizer = model_class.from_pretrained(model_id, subfolder=subfolder)
[2024-11-01 17:58:10] [INFO] File "E:\fluxgym\env\lib\site-packages\transformers\tokenization_utils_base.py", line 2210, in from_pretrained
[2024-11-01 17:58:10] [INFO] tokenizer_config = json.load(reader)
[2024-11-01 17:58:10] [INFO] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
[2024-11-01 17:58:10] [INFO] return loads(fp.read(),
[2024-11-01 17:58:10] [INFO] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
[2024-11-01 17:58:10] [INFO] return _default_decoder.decode(s)
[2024-11-01 17:58:10] [INFO] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
[2024-11-01 17:58:10] [INFO] obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2024-11-01 17:58:10] [INFO] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
[2024-11-01 17:58:10] [INFO] raise JSONDecodeError("Expecting value", s, err.value) from None
[2024-11-01 17:58:10] [INFO] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-11-01 17:58:11] [INFO] Traceback (most recent call last):
[2024-11-01 17:58:11] [INFO] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
[2024-11-01 17:58:11] [INFO] return _run_code(code, main_globals, None,
[2024-11-01 17:58:11] [INFO] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
[2024-11-01 17:58:11] [INFO] exec(code, run_globals)
[2024-11-01 17:58:11] [INFO] File "E:\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-11-01 17:58:11] [INFO] sys.exit(main())
[2024-11-01 17:58:11] [INFO] File "E:\fluxgym\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-11-01 17:58:11] [INFO] args.func(args)
[2024-11-01 17:58:11] [INFO] File "E:\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-11-01 17:58:11] [INFO] simple_launcher(args)
[2024-11-01 17:58:11] [INFO] File "E:\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-11-01 17:58:11] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-11-01 17:58:11] [INFO] subprocess.CalledProcessError: Command '['E:\\fluxgym\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'E:\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'E:\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'E:\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'E:\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'E:\\fluxgym\\outputs\\xb-lora\\dataset.toml', '--output_dir', 'E:\\fluxgym\\outputs\\xb-lora', '--output_name', 'xb-lora', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-11-01 17:58:11] [ERROR] Command exited with code 1
[2024-11-01 17:58:11] [INFO] Runner: <LogsViewRunner nb_logs=56 exit_code=1>

**Comment by Hiddengenie** [comment]
Check whether your ae.sft (in the vae folder) is complete and uncorrupted. If it is then try uploading an older version - I uploaded a version from September and that solved the isse.

**Comment by alexnikospb** [comment]
I have the same problem:  Runner: <LogsViewRunner nb_logs=38 exit_code=1>

**Comment by lesteryebin** [comment]
> Check whether your ae.sft (in the vae folder) is complete and uncorrupted. If it is then try uploading an older version - I uploaded a version from September and that solved the isse.

thank you!

**Comment by Samchris01** [comment]
> Check whether your ae.sft (in the vae folder) is complete and uncorrupted. If it is then try uploading an older version - I uploaded

How to download

**Comment by love9678** [comment]
How to download
