### ISSUE TITLE
support MAC?

### ISSUE THREAD

**Issue by taozhiyuai** [cocktailpeanut/fluxgym#239]
`[2024-11-07 08:33:54] [INFO] INFO     [Dataset 0]                                                                                                                                     config_util.py:576
[2024-11-07 08:33:54] [INFO] INFO     loading image sizes.                                                                                                                             train_util.py:880
[2024-11-07 08:33:54] [INFO] 0%|          | 0/12 [00:00<?, ?it/s]
100%|██████████| 12/12 [00:00<00:00, 31339.76it/s]
[2024-11-07 08:33:54] [INFO] INFO     prepare dataset                                                                                                                                  train_util.py:888
[2024-11-07 08:33:54] [INFO] INFO     preparing accelerator                                                                                                                         train_network.py:345
[2024-11-07 08:33:54] [INFO] Traceback (most recent call last):
[2024-11-07 08:33:54] [INFO] File "/Users/taozhiyu/Downloads/fluxgym.main/sd-scripts/flux_train_network.py", line 519, in <module>
[2024-11-07 08:33:54] [INFO] trainer.train(args)
[2024-11-07 08:33:54] [INFO] File "/Users/taozhiyu/Downloads/fluxgym.main/sd-scripts/train_network.py", line 346, in train
[2024-11-07 08:33:54] [INFO] accelerator = train_util.prepare_accelerator(args)
[2024-11-07 08:33:54] [INFO] File "/Users/taozhiyu/Downloads/fluxgym.main/sd-scripts/library/train_util.py", line 4824, in prepare_accelerator
[2024-11-07 08:33:54] [INFO] accelerator = Accelerator(
[2024-11-07 08:33:54] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages/accelerate/accelerator.py", line 499, in __init__
[2024-11-07 08:33:54] [INFO] raise ValueError("bf16 mixed precision requires PyTorch >= 1.10 and a supported device.")
[2024-11-07 08:33:54] [INFO] ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
[2024-11-07 08:33:54] [INFO] Traceback (most recent call last):
[2024-11-07 08:33:54] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/bin/accelerate", line 8, in <module>
[2024-11-07 08:33:54] [INFO] sys.exit(main())
[2024-11-07 08:33:54] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
[2024-11-07 08:33:54] [INFO] args.func(args)
[2024-11-07 08:33:54] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1106, in launch_command
[2024-11-07 08:33:54] [INFO] simple_launcher(args)
[2024-11-07 08:33:54] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages/accelerate/commands/launch.py", line 704, in simple_launcher
[2024-11-07 08:33:54] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-11-07 08:33:54] [INFO] subprocess.CalledProcessError: Command '['/Users/taozhiyu/miniconda3/envs/fluxgym/bin/python3.10', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', '/Users/taozhiyu/Downloads/fluxgym.main/models/unet/flux1-dev.sft', '--clip_l', '/Users/taozhiyu/Downloads/fluxgym.main/models/clip/clip_l.safetensors', '--t5xxl', '/Users/taozhiyu/Downloads/fluxgym.main/models/clip/t5xxl_fp16.safetensors', '--ae', '/Users/taozhiyu/Downloads/fluxgym.main/models/vae/ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adamw8bit', '--sample_prompts=/Users/taozhiyu/Downloads/fluxgym.main/sample_prompts.txt', '--sample_every_n_steps=10', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', '/Users/taozhiyu/Downloads/fluxgym.main/dataset.toml', '--output_dir', '/Users/taozhiyu/Downloads/fluxgym.main/outputs', '--output_name', 'test', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-11-07 08:33:54] [ERROR] Command exited with code 1
[2024-11-07 08:33:54] [INFO] Runner: <LogsViewRunner nb_logs=80 exit_code=1>`

`(fluxgym) taozhiyu@Mac fluxgym.main % pip3 show torch
Name: torch
Version: 2.4.1`

my Mac is M3 Max. does this project support MAC?

**Comment by taozhiyuai** [comment]
**[2024-11-07 08:33:54] [INFO] raise ValueError("bf16 mixed precision requires PyTorch >= 1.10 and a supported 
device.") **

**[2024-11-07 08:33:54] [INFO] ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.**

**Comment by cauenapier** [comment]
Did you manage to get that running on Mac?

**Comment by taozhiyuai** [comment]
> Did you manage to get that running on Mac?

YES.

**Comment by taozhiyuai** [comment]
```
Flux-schnell-fp8:
    repo: maximsobolev275/flux-fp8-schnell
    base: maximsobolev275/flux-fp8-schnell
    license: apache-2.0
    file: f.1-schnell_fp8_unet_v1.safetensors
Flux-dev-fp8:
    repo: XLabs-AI/flux-dev-fp8
    base: XLabs-AI/flux-dev-fp8
    license: apache-2.0
    file: flux-dev-fp8.safetensors
```


I have tried fp8. still report the same error

**Comment by taozhiyuai** [comment]
`(fluxgym) taozhiyu@Mac fluxgym.main % pip3 show torch
Name: torch
Version: 2.4.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, clean-fid, clip-anytorch, controlnet_aux, dctorch, invisible-watermark, k-diffusion, kornia, lion-pytorch, lpips, lycoris_lora, open_clip_torch, optimum-quanto, peft, pytorch-fid, pytorch-lightning, timm, torchaudio, torchdiffeq, torchmetrics, torchsde, torchvision`

**Comment by taozhiyuai** [comment]
bitsandbytes doesn't support  MAC :(

**Comment by taozhiyuai** [comment]
@cocktailpeanut  can you help me?

**Comment by taozhiyuai** [comment]
[2024-11-29 20:49:02] [INFO] Running bash "/Users/taozhiyu/Downloads/fluxgym.main/outputs/zzz/train.sh"
[2024-11-29 20:49:03] [INFO] The following values were not passed to `accelerate launch` and had defaults used instead:
[2024-11-29 20:49:03] [INFO] `--num_processes` was set to a value of `0`
[2024-11-29 20:49:03] [INFO] `--num_machines` was set to a value of `1`
[2024-11-29 20:49:03] [INFO] `--dynamo_backend` was set to a value of `'no'`
[2024-11-29 20:49:03] [INFO] To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-11-29 20:49:05] [INFO] /Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
[2024-11-29 20:49:05] [INFO] warn("The installed version of bitsandbytes was compiled without GPU support. "
[2024-11-29 20:49:05] [INFO] 'NoneType' object has no attribute 'cadam32bit_grad_fp32'
[2024-11-29 20:49:05] [INFO] 2024-11-29 20:49:05 INFO     highvram is enabled /            train_util.py:4190

**Comment by taozhiyuai** [comment]
> Did you manage to get that running on Mac?

@cauenapier if this project support MAC?

**Comment by taozhiyuai** [comment]
[2024-12-01 11:23:23] [INFO] Running bash "/Users/taozhiyu/Downloads/fluxgym.main/outputs/zzz/train.sh"
[2024-12-01 11:23:25] [INFO] Traceback (most recent call last):
[2024-12-01 11:23:25] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/bin/accelerate", line 8, in <module>
[2024-12-01 11:23:25] [INFO] sys.exit(main())
[2024-12-01 11:23:25] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
[2024-12-01 11:23:25] [INFO] args.func(args)
[2024-12-01 11:23:25] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1084, in launch_command
[2024-12-01 11:23:25] [INFO] args, defaults, mp_from_config_flag = _validate_launch_command(args)
[2024-12-01 11:23:25] [INFO] File "/Users/taozhiyu/miniconda3/envs/fluxgym/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1007, in _validate_launch_command
[2024-12-01 11:23:25] [INFO] raise ValueError("bf16 mixed precision requires PyTorch >= 1.10 and a supported device.")
[2024-12-01 11:23:25] [INFO] ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
[2024-12-01 11:23:25] [ERROR] Command exited with code 1
[2024-12-01 11:23:25] [INFO] Runner: <LogsViewRunner nb_logs=12 exit_code=1>

**Comment by taozhiyuai** [comment]
reason in this issue? https://github.com/bmaltais/kohya_ss/issues/93

**Comment by taozhiyuai** [comment]
@fahadshery @cocktailpeanut reason in this issue? https://github.com/bmaltais/kohya_ss/issues/93

**Comment by taozhiyuai** [comment]
tried solution in https://github.com/bmaltais/kohya_ss/issues/89, still the same error @fahadshery @cocktailpeanut
