### ISSUE TITLE
No module named 'torch.utils._pytree'  on startup, was working fine before

### ISSUE THREAD

**Issue by MiloMindbender** [cocktailpeanut/fluxgym#240]
My install of fluxgym was working fine a few weeks ago, today I tried to start it (from pinokio) and got the error output below.  I tried doing an "update" which brought in a lot of files, but after it was done I got the same startup error.  Any idea how to fix this?

E:\pinokio\api\fluxgym.git>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && E:\pinokio\api\fluxgym.git\env\Scripts\activate E:\pinokio\api\fluxgym.git\env && python app.py
Traceback (most recent call last):
  File "E:\pinokio\api\fluxgym.git\app.py", line 16, in <module>
    from transformers import AutoProcessor, AutoModelForCausalLM
  File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\transformers\utils\generic.py", line 462, in <module>
    import torch.utils._pytree as _torch_pytree
ModuleNotFoundError: No module named 'torch.utils._pytree'

**Comment by MiloMindbender** [comment]
I ended up doing a reinstall to fix this.
