### ISSUE TITLE
Training Flux Loras with CivitAI flux models or other places?

### ISSUE THREAD

**Issue by Nontasz** [cocktailpeanut/fluxgym#243]
Hello everyone, 

I am trying to use a distilled model Coloseus from CivitAI to train a flux lora. The link is : 
https://civitai.com/models/833086/colossus-project-flux
I try to add this model to the model.yaml file, although I can select it at the GUI , the training stops since the repo and base are not in huggingface. 
How I can skip this check and continue with the model which is copied correctly to the models folder? 
Here is the details from the model.yaml file : 

flux-coloseus:
    repo: cocktailpeanut/xulf-dev
    base: black-forest-labs/FLUX.1-dev
    license: other
    license_name: flux-1-dev-non-commercial-license
    license_link: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/LICENSE.md
    file: colossusProjectFlux_21DeDistilledAIOExp.safetensors

The repo and base info I just copy and paste from the other ones, I thought since the model is copied in the right path directory It will be ok, but I get an error that the repo is wrong, here is the error log message : 

Entry Not Found for url: https://huggingface.co/cocktailpeanut/xulf-dev/resolve/main/colossusProjectFlux_21DeDistilledAIOExp.safetensors.

I understand it's the wrong URL for this model, but it exists only on CivitAI and not on huggingface and there is no way to find a valid link to enter there. 

Any help will be much appreciated. 
Thank you.

**Comment by alves-correa** [comment]
Hey bro. Not pretty, but this fixed it for me: 
on app.py, line 335 I added:  unet_folder = "models/unet"

so it looks like this 
```
    # download unet
    if base_model == "flux-dev" or base_model == "flux-schnell":
        unet_folder = "models/unet"
    else:
        unet_folder = f"models/unet/{repo}"
    unet_folder = "models/unet"
```

**Comment by Nontasz** [comment]
> Hey bro. Not pretty, but this fixed it for me: on app.py, line 335 I added: unet_folder = "models/unet"
> 
> so it looks like this
> 
> ```
>     # download unet
>     if base_model == "flux-dev" or base_model == "flux-schnell":
>         unet_folder = "models/unet"
>     else:
>         unet_folder = f"models/unet/{repo}"
>     unet_folder = "models/unet"
> ```

Hey bro! You are the best! It worked! It really worked! I was able to train the lora with Coloseus model! That's really great! 
Thank you so much! 

I only had to add the unet_path in the end, otherwise I was getting an error. So here is the final code that worked for me> 

    # download unet
    if base_model == "flux-dev" or base_model == "flux-schnell":
        unet_folder = "models/unet"
    else:
        unet_folder = f"models/unet/{repo}"
        unet_folder = "models/unet"
    unet_path = os.path.join(unet_folder, model_file)

Would you like to share any helpful important tips for training a Lora? 
Which model are you using to train your Lora for a person? The original Dev Flux is very censored and everytime I use a lora along with my trained Lora at the same prompt , it always affects the quality and the results only reminds a bit of the person I trained the lora with. 
That's the reason I try to use a full capable uncensored Flux model so I won't need any extra Lora apart from the one I trained. 

During the train I use 768 pixels for the resize of the photos, because 512 was not giving me the best quality. How much is your resolution settings for resize? 

Any other tips? maybe for speeding up the process? How many photos do you think it's the minimum to use for a best lora for a person? 

Thank you so much once more!

**Comment by KLL535** [comment]
Why couldn't you just make a textbox with the path to the folder with the models?
Or select the file with the model, as it is done for the pictures.
I have already downloaded the models and don't want to download 16 GB again.
Instead, I have to find the models.yaml file myself and write something incomprehensible there. Where should I write the path to the model file name!? I don't understand.

**Comment by niceguy4** [comment]
> Hey bro. Not pretty, but this fixed it for me: on app.py, line 335 I added: unet_folder = "models/unet"
> 
> so it looks like this
> 
> ```
>     # download unet
>     if base_model == "flux-dev" or base_model == "flux-schnell":
>         unet_folder = "models/unet"
>     else:
>         unet_folder = f"models/unet/{repo}"
>     unet_folder = "models/unet"
> ```

Thank you!



> Why couldn't you just make a textbox with the path to the folder with the models? Or select the file with the model, as it is done for the pictures. I have already downloaded the models and don't want to download 16 GB again. Instead, I have to find the models.yaml file myself and write something incomprehensible there. Where should I write the path to the model file name!? I don't understand.

The app.py is here, C:\pinokio\api\fluxgym.git\
Add this code that is bold and underlined below

    if base_model == "flux-dev" or base_model == "flux-schnell":
        unet_folder = "models/unet"
    else:
        unet_folder = f"models/unet/{repo}"
    _**unet_folder = "models/unet"**_

The models.yaml is here, C:\pinokio\api\fluxgym.git\

Example of a custom model that I added to the bottom of the yaml file. Fluxgym will fail unless you add the code in this comment above.

getphatFLUXReality_v30:
    file: getphatFLUXReality_v30.safetensors

The models can be manually added here, C:\pinokio\api\fluxgym.git\models\unet\

**Comment by normanew** [comment]
I've getting some errors even though I added the code to my app.py and the models.py

`Traceback (most recent call last):
  File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api  
    result = await self.call_function(
  File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync     
    return await get_async_backend().run_sync_in_worker_thread(
  File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\utils.py", line 826, in wrapper        
    response = f(*args, **kwargs)
  File "G:\pinokio\api\fluxgym.git\app.py", line 665, in update
    sh = gen_sh(
  File "G:\pinokio\api\fluxgym.git\app.py", line 443, in gen_sh
    repo = model_config["repo"]
KeyError: 'repo'`

**Comment by niceguy4** [comment]
> I've getting some errors even though I added the code to my app.py and the models.py
> 
> ```
> Traceback (most recent call last):
>   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
>     response = await route_utils.call_process_api(
>   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api  
>     result = await self.call_function(
>   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
>     prediction = await anyio.to_thread.run_sync(  # type: ignore
>   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync     
>     return await get_async_backend().run_sync_in_worker_thread(
>   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
>     return await future
>   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
>     result = context.run(func, *args)
>   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\utils.py", line 826, in wrapper        
>     response = f(*args, **kwargs)
>   File "G:\pinokio\api\fluxgym.git\app.py", line 665, in update
>     sh = gen_sh(
>   File "G:\pinokio\api\fluxgym.git\app.py", line 443, in gen_sh
>     repo = model_config["repo"]
> KeyError: 'repo'
> ```

Did you edit the models.yaml  file, too?

**Comment by normanew** [comment]
> > I've getting some errors even though I added the code to my app.py and the models.py
> > ```
> > Traceback (most recent call last):
> >   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
> >     response = await route_utils.call_process_api(
> >   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
> >     output = await app.get_blocks().process_api(
> >   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api  
> >     result = await self.call_function(
> >   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
> >     prediction = await anyio.to_thread.run_sync(  # type: ignore
> >   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync     
> >     return await get_async_backend().run_sync_in_worker_thread(
> >   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
> >     return await future
> >   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
> >     result = context.run(func, *args)
> >   File "G:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\utils.py", line 826, in wrapper        
> >     response = f(*args, **kwargs)
> >   File "G:\pinokio\api\fluxgym.git\app.py", line 665, in update
> >     sh = gen_sh(
> >   File "G:\pinokio\api\fluxgym.git\app.py", line 443, in gen_sh
> >     repo = model_config["repo"]
> > KeyError: 'repo'
> > ```
> 
> Did you edit the models.yaml file, too?

Yes, i've tried using the same model and the models.yaml as you provided above.
```
getphatFLUXReality_v30:
    file: getphatFLUXReality_v30.safetensors
```

**Comment by Autantpourmoi** [comment]
tried also your code , my custom model  is able to be selected in the dropping menu,  but i lost the train script and train config presets and both windows return errors . Any idea ?
