### ISSUE TITLE
How do I fix this error IndexError: tuple index out of range

### ISSUE THREAD

**Issue by qiujinx** [cocktailpeanut/fluxgym#258]
Traceback (most recent call last):
  File "D:\Fluxgym\fluxgym\fluxgym\python_embeded\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\Fluxgym\fluxgym\fluxgym\python_embeded\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Fluxgym\fluxgym\fluxgym\python_embeded\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\Fluxgym\fluxgym\fluxgym\python_embeded\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\Fluxgym\fluxgym\fluxgym\python_embeded\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Fluxgym\fluxgym\fluxgym\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "D:\Fluxgym\fluxgym\fluxgym\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "D:\Fluxgym\fluxgym\fluxgym\python_embeded\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\Fluxgym\fluxgym\fluxgym\fluxgym\app.py", line 252, in create_dataset
    original_caption = inputs[index + 1]
IndexError: tuple index out of range
concept_sentence=xijie_sbpk
lora_name sbpk, concept_sentence=xijie_sbpk, output_name=sbpk
license_items=['license: other', 'license_name: flux-1-dev-non-commercial-license', 'license_link: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/LICENSE.md']
license_str = license: other
license_name: flux-1-dev-non-commercial-license
license_link: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/LICENSE.md
no samples
I made this mistake during training

**Comment by AlexFeYang** [comment]
getting the same error, when I put a larger dataset(over maybe 76 images) will 100% get this error,
I meet the same error at ai-toolkit, it will kill the training process at the beginning
I think it is due to the gradio did not upload all the files(I check the dataset folder, it has only 76 while I upload 100 images)

**Comment by xijiee** [comment]
I tried to train with 50 images and it worked, it seems there are too many images
Thank you


> getting the same error, when I put a larger dataset(over maybe 76 images) will 100% get this error, I meet the same error at ai-toolkit, it will kill the training process at the beginning I think it is due to the gradio did not upload all the files(I check the dataset folder, it has only 76 while I upload 100 images)

**Comment by Edwinswanith** [comment]
Is there any solution for it?
