### ISSUE TITLE
libpng missing ubuntu 24.04.4

### ISSUE THREAD

**Issue by billysb** [cocktailpeanut/fluxgym#26]
Missing lib dependencies cause fluxgym to fail to start training with the following exceptions:

> [2024-09-08 12:06:21] [INFO] Running bash "/pinokio/api/fluxgym.git/train.sh"
> [2024-09-08 12:06:24] [INFO] The following values were not passed to `accelerate launch` and had defaults used instead:
> [2024-09-08 12:06:24] [INFO] `--num_processes` was set to a value of `2`
> [2024-09-08 12:06:24] [INFO] More than one GPU was found, enabling multi-GPU training.
> [2024-09-08 12:06:24] [INFO] If this was unintended please pass in `--num_processes=1`.
> [2024-09-08 12:06:24] [INFO] `--num_machines` was set to a value of `1`
> [2024-09-08 12:06:24] [INFO] `--dynamo_backend` was set to a value of `'no'`
> [2024-09-08 12:06:24] [INFO] To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
> [2024-09-08 12:06:26] [INFO] Traceback (most recent call last):
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/sd-scripts/flux_train_network.py", line 13, in <module>
> [2024-09-08 12:06:26] [INFO] from library import flux_models, flux_train_utils, flux_utils, sd3_train_utils, strategy_base, strategy_flux, train_util
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/sd-scripts/library/flux_train_utils.py", line 17, in <module>
> [2024-09-08 12:06:26] [INFO] from library import flux_models, flux_utils, strategy_base, train_util
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/sd-scripts/library/flux_utils.py", line 12, in <module>
> [2024-09-08 12:06:26] [INFO] from library.utils import setup_logging, MemoryEfficientSafeOpen
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/sd-scripts/library/utils.py", line 13, in <module>
> [2024-09-08 12:06:26] [INFO] import cv2
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
> [2024-09-08 12:06:26] [INFO] bootstrap()
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
> [2024-09-08 12:06:26] [INFO] native_module = importlib.import_module("cv2")
> [2024-09-08 12:06:26] [INFO] File "/pinokio/bin/miniconda/lib/python3.10/importlib/__init__.py", line 126, in import_module
> [2024-09-08 12:06:26] [INFO] return _bootstrap._gcd_import(name[level:], package, level)
> [2024-09-08 12:06:26] [INFO] ImportError: libpng16-1bde1c40.so.16.43.0: cannot open shared object file: No such file or directory
> [2024-09-08 12:06:26] [INFO] Traceback (most recent call last):
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/sd-scripts/flux_train_network.py", line 13, in <module>
> [2024-09-08 12:06:26] [INFO] from library import flux_models, flux_train_utils, flux_utils, sd3_train_utils, strategy_base, strategy_flux, train_util
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/sd-scripts/library/flux_train_utils.py", line 17, in <module>
> [2024-09-08 12:06:26] [INFO] from library import flux_models, flux_utils, strategy_base, train_util
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/sd-scripts/library/flux_utils.py", line 12, in <module>
> [2024-09-08 12:06:26] [INFO] from library.utils import setup_logging, MemoryEfficientSafeOpen
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/sd-scripts/library/utils.py", line 13, in <module>
> [2024-09-08 12:06:26] [INFO] import cv2
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
> [2024-09-08 12:06:26] [INFO] bootstrap()
> [2024-09-08 12:06:26] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
> [2024-09-08 12:06:26] [INFO] native_module = importlib.import_module("cv2")
> [2024-09-08 12:06:26] [INFO] File "/pinokio/bin/miniconda/lib/python3.10/importlib/__init__.py", line 126, in import_module
> [2024-09-08 12:06:26] [INFO] return _bootstrap._gcd_import(name[level:], package, level)
> [2024-09-08 12:06:26] [INFO] ImportError: libpng16-1bde1c40.so.16.43.0: cannot open shared object file: No such file or directory
> [2024-09-08 12:06:27] [INFO] [2024-09-08 12:06:27,384] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 318821) of binary: /pinokio/api/fluxgym.git/env/bin/python
> [2024-09-08 12:06:27] [INFO] Traceback (most recent call last):
> [2024-09-08 12:06:27] [INFO] File "/pinokio/api/fluxgym.git/env/bin/accelerate", line 8, in <module>
> [2024-09-08 12:06:27] [INFO] sys.exit(main())
> [2024-09-08 12:06:27] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
> [2024-09-08 12:06:27] [INFO] args.func(args)
> [2024-09-08 12:06:27] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
> [2024-09-08 12:06:27] [INFO] multi_gpu_launcher(args)
> [2024-09-08 12:06:27] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 734, in multi_gpu_launcher
> [2024-09-08 12:06:27] [INFO] distrib_run.run(args)
> [2024-09-08 12:06:27] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
> [2024-09-08 12:06:27] [INFO] elastic_launch(
> [2024-09-08 12:06:27] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
> [2024-09-08 12:06:27] [INFO] return launch_agent(self._config, self._entrypoint, list(args))
> [2024-09-08 12:06:27] [INFO] File "/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
> [2024-09-08 12:06:27] [INFO] raise ChildFailedError(
> [2024-09-08 12:06:27] [INFO] torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> [2024-09-08 12:06:27] [INFO] ============================================================
> [2024-09-08 12:06:27] [INFO] sd-scripts/flux_train_network.py FAILED
> [2024-09-08 12:06:27] [INFO] ------------------------------------------------------------
> [2024-09-08 12:06:27] [INFO] Failures:
> [2024-09-08 12:06:27] [INFO] [1]:
> [2024-09-08 12:06:27] [INFO] time      : 2024-09-08_12:06:27
> [2024-09-08 12:06:27] [INFO] host      : printer
> [2024-09-08 12:06:27] [INFO] rank      : 1 (local_rank: 1)
> [2024-09-08 12:06:27] [INFO] exitcode  : 1 (pid: 318822)
> [2024-09-08 12:06:27] [INFO] error_file: <N/A>
> [2024-09-08 12:06:27] [INFO] traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [2024-09-08 12:06:27] [INFO] ------------------------------------------------------------
> [2024-09-08 12:06:27] [INFO] Root Cause (first observed failure):
> [2024-09-08 12:06:27] [INFO] [0]:
> [2024-09-08 12:06:27] [INFO] time      : 2024-09-08_12:06:27
> [2024-09-08 12:06:27] [INFO] host      : printer
> [2024-09-08 12:06:27] [INFO] rank      : 0 (local_rank: 0)
> [2024-09-08 12:06:27] [INFO] exitcode  : 1 (pid: 318821)
> [2024-09-08 12:06:27] [INFO] error_file: <N/A>
> [2024-09-08 12:06:27] [INFO] traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [2024-09-08 12:06:27] [INFO] ============================================================
> [2024-09-08 12:06:27] [ERROR] Command exited with code 1
> [2024-09-08 12:06:27] [INFO] Runner: <LogsViewRunner nb_logs=79 exit_code=1>

It doesn't look super obvious on how to solve this without installing the dependency manually?

**Comment by billysb** [comment]
This seems like an installer issue? I have other pinokio projects that have this lib:
/pinokio/api/triposr.git/app/env/lib/libpng16.so.16.43.0

**Comment by billysb** [comment]
Turns out its an issue with Pinokio installing manually has no issues with this.

**Comment by csprsmt** [comment]
Where should be installed?

**Comment by billysb** [comment]
> Where should it be installed?

honestly it worked fine once I manually installed the github repo. try following the instructions in the read me it should work unless your distro is actually missing the libs.
