### ISSUE TITLE
I installed it on Ubuntu and encountered an error while running FluxGym

### ISSUE THREAD

**Issue by Tucakang** [cocktailpeanut/fluxgym#261]
Traceback (most recent call last):
  File "/home/server/liandan/fluxgym/app.py", line 9, in <module>
    import gradio as gr
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/gradio/processing_utils.py", line 99, in <module>
    sync_client = httpx.Client(transport=sync_transport)
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/httpx/_client.py", line 686, in __init__
    proxy_map = self._get_proxy_map(proxy, allow_env_proxies)
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/httpx/_client.py", line 244, in _get_proxy_map
    return {
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/httpx/_client.py", line 245, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/server/liandan/fluxgym/env/lib/python3.10/site-packages/httpx/_config.py", line 214, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7891/')

**Comment by FruitPigFoot** [comment]
are you trying to run it on remote server?

**Comment by heytony965342** [comment]
unset all_proxy
unset http_proxy
unset https_proxy
