### ISSUE TITLE
running fluxgym in pinokio getting an error 

### ISSUE THREAD

**Issue by kirinkarei** [cocktailpeanut/fluxgym#269]
i get this error every time

[2024-12-18 21:00:09] [INFO] Traceback (most recent call last):
[2024-12-18 21:00:09] [INFO] File "E:\pinokio\Nueva\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
[2024-12-18 21:00:09] [INFO] return _run_code(code, main_globals, None,
[2024-12-18 21:00:09] [INFO] File "E:\pinokio\Nueva\bin\miniconda\lib\runpy.py", line 86, in _run_code
[2024-12-18 21:00:09] [INFO] exec(code, run_globals)
[2024-12-18 21:00:09] [INFO] File "E:\pinokio\Nueva\api\fluxgym.git\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-12-18 21:00:09] [INFO] sys.exit(main())
[2024-12-18 21:00:09] [INFO] File "E:\pinokio\Nueva\api\fluxgym.git\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-12-18 21:00:09] [INFO] args.func(args)
[2024-12-18 21:00:09] [INFO] File "E:\pinokio\Nueva\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-12-18 21:00:09] [INFO] simple_launcher(args)
[2024-12-18 21:00:09] [INFO] File "E:\pinokio\Nueva\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-12-18 21:00:09] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-12-18 21:00:09] [INFO] subprocess.CalledProcessError: Command '['E:\\pinokio\\Nueva\\api\\fluxgym.git\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'E:\\pinokio\\Nueva\\api\\fluxgym.git\\models\\unet\\flux1-schnell.safetensors', '--clip_l', 'E:\\pinokio\\Nueva\\api\\fluxgym.git\\models\\clip\\clip_l.safetensors', '--t5xxl', 'E:\\pinokio\\Nueva\\api\\fluxgym.git\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'E:\\pinokio\\Nueva\\api\\fluxgym.git\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--sample_prompts=E:\\pinokio\\Nueva\\api\\fluxgym.git\\outputs\\frd-frd\\sample_prompts.txt', '--sample_every_n_steps=272', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'E:\\pinokio\\Nueva\\api\\fluxgym.git\\outputs\\frd-frd\\dataset.toml', '--output_dir', 'E:\\pinokio\\Nueva\\api\\fluxgym.git\\outputs\\frd-frd', '--output_name', 'frd-frd', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 3221225477.
[2024-12-18 21:00:11] [ERROR] Command exited with code 1
[2024-12-18 21:00:11] [INFO] Runner: <LogsViewRunner nb_logs=139 exit_code=1>

**Comment by MarkusZiegler** [comment]
Hi, same here.
What do I do?
Please help.

**Comment by hieuck** [comment]
same on Stability Matrix
[2025-01-06 18:34:24] [INFO] Running G:\StabilityMatrix\Data\Packages\FluxGym\outputs\gauden\train.bat
[2025-01-06 18:34:24] [INFO] 
[2025-01-06 18:34:24] [INFO] G:\StabilityMatrix\Data\Packages\FluxGym>accelerate launch   --mixed_precision bf16   --num_cpu_threads_per_process 1   sd-scripts/flux_train_network.py   --pretrained_model_name_or_path "G:\StabilityMatrix\Data\Packages\FluxGym\models\unet\flux1-dev.sft"   --clip_l "G:\StabilityMatrix\Data\Packages\FluxGym\models\clip\clip_l.safetensors"   --t5xxl "G:\StabilityMatrix\Data\Packages\FluxGym\models\clip\t5xxl_fp16.safetensors"   --ae "G:\StabilityMatrix\Data\Packages\FluxGym\models\vae\ae.sft"   --cache_latents_to_disk   --save_model_as safetensors   --sdpa --persistent_data_loader_workers   --max_data_loader_n_workers 2   --seed 42   --gradient_checkpointing   --mixed_precision bf16   --save_precision bf16   --network_module networks.lora_flux   --network_dim 4   --optimizer_type adafactor   --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False"   --split_mode   --network_args "train_blocks=single"   --lr_scheduler constant_with_warmup   --max_grad_norm 0.0   --learning_rate 8e-4   --cache_text_encoder_outputs   --cache_text_encoder_outputs_to_disk   --fp8_base   --highvram   --max_train_epochs 16   --save_every_n_epochs 4   --dataset_config "G:\StabilityMatrix\Data\Packages\FluxGym\outputs\gauden\dataset.toml"   --output_dir "G:\StabilityMatrix\Data\Packages\FluxGym\outputs\gauden"   --output_name gauden   --timestep_sampling shift   --discrete_flow_shift 3.1582   --model_prediction_type raw   --guidance_scale 1   --loss_type l2
[2025-01-06 18:34:42] [INFO] 2025-01-06 18:34:42 INFO     highvram is enabled /           train_util.py:4199
[2025-01-06 18:34:42] [INFO] highvramが有効です
[2025-01-06 18:34:42] [INFO] WARNING  cache_latents_to_disk is        train_util.py:4216
[2025-01-06 18:34:42] [INFO] enabled, so cache_latents is
[2025-01-06 18:34:42] [INFO] also enabled /
[2025-01-06 18:34:42] [INFO] cache_latents_to_diskが有効なた
[2025-01-06 18:34:42] [INFO] め、cache_latentsを有効にします
[2025-01-06 18:34:42] [INFO] 2025-01-06 18:34:42 INFO     Checking the state dict:          flux_utils.py:43
[2025-01-06 18:34:42] [INFO] Diffusers or BFL, dev or schnell
[2025-01-06 18:34:43] [INFO] 2025-01-06 18:34:43 INFO     t5xxl_max_token_length:  flux_train_network.py:150
[2025-01-06 18:34:43] [INFO] 512
[2025-01-06 18:34:43] [INFO] G:\StabilityMatrix\Data\Packages\FluxGym\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
[2025-01-06 18:34:43] [INFO] warnings.warn(
[2025-01-06 18:34:44] [INFO] You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
[2025-01-06 18:34:44] [INFO] 2025-01-06 18:34:44 INFO     Loading dataset config from   train_network.py:339
[2025-01-06 18:34:44] [INFO] G:\StabilityMatrix\Data\Packa
[2025-01-06 18:34:44] [INFO] ges\FluxGym\outputs\gauden\da
[2025-01-06 18:34:44] [INFO] taset.toml
[2025-01-06 18:34:44] [INFO] INFO     prepare images.                 train_util.py:1971
[2025-01-06 18:34:44] [INFO] INFO     get image size from name of     train_util.py:1886
[2025-01-06 18:34:44] [INFO] cache files
[2025-01-06 18:34:44] [INFO] 0%|          | 0/23 [00:00<?, ?it/s]
100%|██████████| 23/23 [00:00<?, ?it/s]
[2025-01-06 18:34:44] [INFO] INFO     set image size from cache       train_util.py:1916
[2025-01-06 18:34:44] [INFO] files: 0/23
[2025-01-06 18:34:44] [INFO] INFO     found directory                 train_util.py:1918
[2025-01-06 18:34:44] [INFO] G:\StabilityMatrix\Data\Package
[2025-01-06 18:34:44] [INFO] s\FluxGym\datasets\gauden
[2025-01-06 18:34:44] [INFO] contains 23 image files
[2025-01-06 18:34:44] [INFO] read caption:   0%|          | 0/23 [00:00<?, ?it/s]                    ERROR    illegal char in file (not       train_util.py:1843
[2025-01-06 18:34:44] [INFO] UTF-8) /
[2025-01-06 18:34:44] [INFO] ファイルにUTF-8以外の文字があり
[2025-01-06 18:34:44] [INFO] ます:
[2025-01-06 18:34:44] [INFO] G:\StabilityMatrix\Data\Package
[2025-01-06 18:34:44] [INFO] s\FluxGym\datasets\gauden\gau
[2025-01-06 18:34:44] [INFO] den_2020-10-13_00005.txt
[2025-01-06 18:34:44] [INFO] read caption:  17%|█▋        | 4/23 [00:00<00:00, 68.27it/s]
[2025-01-06 18:34:44] [INFO] Traceback (most recent call last):
[2025-01-06 18:34:44] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\sd-scripts\flux_train_network.py", line 583, in <module>
[2025-01-06 18:34:44] [INFO] trainer.train(args)
[2025-01-06 18:34:44] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\sd-scripts\train_network.py", line 376, in train
[2025-01-06 18:34:44] [INFO] train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
[2025-01-06 18:34:44] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\sd-scripts\library\config_util.py", line 481, in generate_dataset_group_by_blueprint
[2025-01-06 18:34:44] [INFO] dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
[2025-01-06 18:34:44] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\sd-scripts\library\train_util.py", line 1988, in __init__
[2025-01-06 18:34:44] [INFO] img_paths, captions, sizes = load_dreambooth_dir(subset)
[2025-01-06 18:34:44] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\sd-scripts\library\train_util.py", line 1928, in load_dreambooth_dir
[2025-01-06 18:34:44] [INFO] cap_for_img = read_caption(img_path, subset.caption_extension, subset.enable_wildcard)
[2025-01-06 18:34:44] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\sd-scripts\library\train_util.py", line 1844, in read_caption
[2025-01-06 18:34:44] [INFO] raise e
[2025-01-06 18:34:44] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\sd-scripts\library\train_util.py", line 1841, in read_caption
[2025-01-06 18:34:44] [INFO] lines = f.readlines()
[2025-01-06 18:34:44] [INFO] File "codecs.py", line 322, in decode
[2025-01-06 18:34:44] [INFO] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 57: invalid continuation byte
[2025-01-06 18:34:45] [INFO] Traceback (most recent call last):
[2025-01-06 18:34:45] [INFO] File "runpy.py", line 196, in _run_module_as_main
[2025-01-06 18:34:45] [INFO] File "runpy.py", line 86, in _run_code
[2025-01-06 18:34:45] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2025-01-06 18:34:45] [INFO] sys.exit(main())
[2025-01-06 18:34:45] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2025-01-06 18:34:45] [INFO] args.func(args)
[2025-01-06 18:34:45] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2025-01-06 18:34:45] [INFO] simple_launcher(args)
[2025-01-06 18:34:45] [INFO] File "G:\StabilityMatrix\Data\Packages\FluxGym\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2025-01-06 18:34:45] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2025-01-06 18:34:45] [INFO] subprocess.CalledProcessError: Command '['G:\\StabilityMatrix\\Data\\Packages\\FluxGym\\venv\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'G:\\StabilityMatrix\\Data\\Packages\\FluxGym\\models\\unet\\flux1-dev.sft', '--clip_l', 'G:\\StabilityMatrix\\Data\\Packages\\FluxGym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'G:\\StabilityMatrix\\Data\\Packages\\FluxGym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'G:\\StabilityMatrix\\Data\\Packages\\FluxGym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'G:\\StabilityMatrix\\Data\\Packages\\FluxGym\\outputs\\gauden\\dataset.toml', '--output_dir', 'G:\\StabilityMatrix\\Data\\Packages\\FluxGym\\outputs\\gauden', '--output_name', 'gauden', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2025-01-06 18:34:46] [ERROR] Command exited with code 1
[2025-01-06 18:34:46] [INFO] Runner: <LogsViewRunner nb_logs=69 exit_code=1>

**Comment by Nemlet17** [comment]
Same error here!

**Comment by pbradjr99** [comment]
anything solutions yet, same problem here
