### ISSUE TITLE
"NameError: name 'unicode' is not defined"  Help

### ISSUE THREAD

**Issue by zlix0000** [cocktailpeanut/fluxgym#281]
NameError: name 'unicode' is not defined
Traceback (most recent call last):
  File "D:\_Gen\fgym\system\python\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\_Gen\fgym\system\python\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\_Gen\fgym\system\python\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\_Gen\fgym\system\python\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\_Gen\fgym\system\python\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\_Gen\fgym\system\python\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "D:\_Gen\fgym\system\python\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "D:\_Gen\fgym\system\python\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\_Gen\fgym\app.py", line 560, in get_samples

**Comment by ffhelly** [comment]
same

**Comment by wind8754** [comment]
same
