### ISSUE TITLE
Trains stops after some steps

### ISSUE THREAD

**Issue by andreacostigliolo** [cocktailpeanut/fluxgym#29]
Hello, 
I've a strange error. Training stops after some steps (not always the same one....) : 4070 12GB

Error : 

steps:   1%|          | 17/2100 [01:56<3:57:22,  6.84s/it, avr_loss=0.343]
steps:   1%|          | 18/2100 [02:01<3:54:41,  6.76s/it, avr_loss=0.343]
steps:   1%|          | 18/2100 [02:01<3:55:01,  6.77s/it, avr_loss=0.343]
steps:   1%|          | 19/2100 [02:07<3:52:54,  6.72s/it, avr_loss=0.343]
steps:   1%|          | 19/2100 [02:07<3:53:14,  6.72s/it, avr_loss=0.353]
steps:   1%|          | 20/2100 [02:13<3:51:57,  6.69s/it, avr_loss=0.353]
steps:   1%|          | 20/2100 [02:13<3:52:15,  6.70s/it, avr_loss=0.35] 
steps:   1%|          | 21/2100 [02:19<3:50:38,  6.66s/it, avr_loss=0.35]
steps:   1%|          | 21/2100 [02:19<3:50:55,  6.66s/it, avr_loss=0.357]
steps:   1%|          | 22/2100 [02:25<3:49:05,  6.61s/it, avr_loss=0.357]
steps:   1%|          | 22/2100 [02:25<3:49:20,  6.62s/it, avr_loss=0.357]
steps:   1%|          | 23/2100 [02:31<3:47:42,  6.58s/it, avr_loss=0.357]
steps:   1%|          | 23/2100 [02:31<3:47:56,  6.58s/it, avr_loss=0.363]
steps:   1%|          | 24/2100 [02:36<3:46:12,  6.54s/it, avr_loss=0.363]
steps:   1%|          | 24/2100 [02:37<3:46:28,  6.55s/it, avr_loss=0.36] 
steps:   1%|          | 25/2100 [02:42<3:45:06,  6.51s/it, avr_loss=0.36]
steps:   1%|          | 25/2100 [02:42<3:45:19,  6.52s/it, avr_loss=0.358]
steps:   1%|          | 26/2100 [02:48<3:44:02,  6.48s/it, avr_loss=0.358]
steps:   1%|          | 26/2100 [02:48<3:44:15,  6.49s/it, avr_loss=0.356]
steps:   1%|▏         | 27/2100 [02:54<3:43:23,  6.47s/it, avr_loss=0.356]
steps:   1%|▏         | 27/2100 [02:54<3:43:44,  6.48s/it, avr_loss=0.362]
steps:   1%|▏         | 28/2100 [03:00<3:42:44,  6.45s/it, avr_loss=0.362]
steps:   1%|▏         | 28/2100 [03:00<3:42:57,  6.46s/it, avr_loss=0.362]
steps:   1%|▏         | 29/2100 [03:06<3:42:00,  6.43s/it, avr_loss=0.362]Traceback (most recent call last):
[2024-09-08 15:42:00] [INFO] File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
[2024-09-08 15:42:00] [INFO] return _run_code(code, main_globals, None,
[2024-09-08 15:42:00] [INFO] File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
[2024-09-08 15:42:00] [INFO] exec(code, run_globals)
[2024-09-08 15:42:00] [INFO] File "D:\Fluxgym\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-08 15:42:00] [INFO] File "D:\Fluxgym\fluxgym\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-08 15:42:00] [INFO] args.func(args)
[2024-09-08 15:42:00] [INFO] File "D:\Fluxgym\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-08 15:42:00] [INFO] simple_launcher(args)
[2024-09-08 15:42:00] [INFO] File "D:\Fluxgym\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-08 15:42:00] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-08 15:42:00] [INFO] subprocess.CalledProcessError: Command '['D:\\Fluxgym\\fluxgym\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'D:\\Fluxgym\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'D:\\Fluxgym\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'D:\\Fluxgym\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'D:\\Fluxgym\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '10', '--save_every_n_epochs', '4', '--dataset_config', 'D:\\Fluxgym\\fluxgym\\dataset.toml', '--output_dir', 'D:\\Fluxgym\\fluxgym\\outputs', '--output_name', 'dark-comic', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 3221225477.
[2024-09-08 15:42:04] [ERROR] Command exited with code 3221225477
[2024-09-08 15:42:04] [INFO] Runner: <LogsViewRunner nb_logs=198 exit_code=3221225477>

Thanks

**Comment by andreacostigliolo** [comment]
Please close issue. Found a problem on my installation and now it works.
