### ISSUE TITLE
cannot load captions from files

### ISSUE THREAD

**Issue by zadokov** [cocktailpeanut/fluxgym#30]
When you load images + text captions the matching of captions to images is done properly but the script considers all files (images + text captions) as images and training fail when trying to resize a caption text file....

Traceback (most recent call last):
  File "C:\SD\fluxgym\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\SD\fluxgym\env\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\SD\fluxgym\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\SD\fluxgym\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\SD\fluxgym\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\SD\fluxgym\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\SD\fluxgym\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\SD\fluxgym\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\SD\fluxgym\app_org.py", line 93, in create_dataset
    resize_image(new_image_path, new_image_path, size)
  File "C:\SD\fluxgym\app_org.py", line 70, in resize_image
    with Image.open(image_path) as img:
  File "C:\SD\fluxgym\env\lib\site-packages\PIL\Image.py", line 3498, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'C:\\SD\\fluxgym\\datasets\\jc-flx-07\\00122-2556933555 copy.txt'launched

**Comment by Mixomo** [comment]
Same error.... The training runs but I'm afraid that this error affect the results...
