### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by evilalmus** [cocktailpeanut/fluxgym#34]
I'm getting the following error when I try to start training. Can anyone help? 
GPU: 3090 24g
RAM: 64g

[2024-09-08 13:42:58] [INFO] File "P:\fluxgym\sd-scripts\flux_train_network.py", line 519, in <module>
[2024-09-08 13:42:58] [INFO] trainer.train(args)
[2024-09-08 13:42:58] [INFO] File "P:\fluxgym\sd-scripts\train_network.py", line 402, in train
[2024-09-08 13:42:58] [INFO] self.cache_text_encoder_outputs_if_needed(args, accelerator, unet, vae, text_encoders, train_dataset_group, weight_dtype)
[2024-09-08 13:42:58] [INFO] File "P:\fluxgym\sd-scripts\flux_train_network.py", line 217, in cache_text_encoder_outputs_if_needed
[2024-09-08 13:42:58] [INFO] text_encoders[0].to(accelerator.device, dtype=weight_dtype)  # always not fp8
[2024-09-08 13:42:58] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-08 13:42:58] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\transformers\modeling_utils.py", line 2883, in to
[2024-09-08 13:42:58] [INFO] return super().to(*args, **kwargs)
[2024-09-08 13:42:58] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-08 13:42:58] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
[2024-09-08 13:42:58] [INFO] return self._apply(convert)
[2024-09-08 13:42:58] [INFO] ^^^^^^^^^^^^^^^^^^^^
[2024-09-08 13:42:58] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
[2024-09-08 13:42:58] [INFO] module._apply(fn)
[2024-09-08 13:42:58] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
[2024-09-08 13:42:58] [INFO] module._apply(fn)
[2024-09-08 13:42:58] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
[2024-09-08 13:42:58] [INFO] module._apply(fn)
[2024-09-08 13:42:58] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
[2024-09-08 13:42:58] [INFO] param_applied = fn(param)
[2024-09-08 13:42:58] [INFO] ^^^^^^^^^
[2024-09-08 13:42:58] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\torch\nn\modules\module.py", line 1333, in convert
[2024-09-08 13:42:58] [INFO] raise NotImplementedError(
[2024-09-08 13:42:58] [INFO] NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
[2024-09-08 13:42:59] [INFO] Traceback (most recent call last):
[2024-09-08 13:42:59] [INFO] File "<frozen runpy>", line 198, in _run_module_as_main
[2024-09-08 13:42:59] [INFO] File "<frozen runpy>", line 88, in _run_code
[2024-09-08 13:42:59] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-08 13:42:59] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-08 13:42:59] [INFO] args.func(args)
[2024-09-08 13:42:59] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-08 13:42:59] [INFO] simple_launcher(args)
[2024-09-08 13:42:59] [INFO] File "C:\Users\evila\.conda\envs\fluxgym\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-08 13:42:59] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-08 13:42:59] [INFO] subprocess.CalledProcessError: Command '['C:\\Users\\evila\\.conda\\envs\\fluxgym\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'P:\\ComfyUI\\models\\unet\\flux1-dev.sft', '--clip_l', 'P:\\ComfyUI\\models\\clip\\clip_l.safetensors', '--t5xxl', 'P:\\ComfyUI\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'P:\\ComfyUI\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'P:\\fluxgym\\dataset.toml', '--output_dir', 'P:\\fluxgym\\outputs', '--output_name', 'almuslora', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-09-08 13:42:59] [ERROR] Command exited with code 1
[2024-09-08 13:42:59] [INFO] Runner: <LogsViewRunner nb_logs=1414 exit_code=1>

**Comment by andygock** [comment]
Did you find a solution?

I have the same problem.

**Comment by Siavee-uni** [comment]
Had the same error if i used a different base model. To bad i cant use other ceckpoints

**Comment by andygock** [comment]
@Siavee-uni For me, I worked it out too, I was using the wrong VAE (a smaller fp16 one) instead of the official one. Once I used the right one, problem went away.

**Comment by songlijiang2024** [comment]
I have the same problem. Can anyone help?

[2025-02-10 16:22:21] [INFO] 2025-02-10 16:22:21 INFO     Building CLIP-L                                                                                                          flux_utils.py:179
[2025-02-10 16:22:21] [INFO] 2025-02-10 16:22:21 INFO     Building CLIP-L                                                                                                          flux_utils.py:179
[2025-02-10 16:22:21] [INFO] [2025-02-10 16:22:21,359] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
[2025-02-10 16:22:21] [INFO] [2025-02-10 16:22:21,359] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
[2025-02-10 16:22:21] [INFO] [rank2]: Traceback (most recent call last):
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data3/home/work/songlijiang/fluxgym/sd-scripts/flux_train_network.py", line 622, in <module>
[2025-02-10 16:22:21] [INFO] [rank2]:     trainer.train(args)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data3/home/work/songlijiang/fluxgym/sd-scripts/train_network.py", line 529, in train
[2025-02-10 16:22:21] [INFO] [rank2]:     model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data3/home/work/songlijiang/fluxgym/sd-scripts/flux_train_network.py", line 129, in load_target_model
[2025-02-10 16:22:21] [INFO] [rank2]:     clip_l = flux_utils.load_clip_l(
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data3/home/work/songlijiang/fluxgym/sd-scripts/library/flux_utils.py", line 270, in load_clip_l
[2025-02-10 16:22:21] [INFO] [rank2]:     clip = CLIPTextModel._from_config(config)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1475, in _from_config
[2025-02-10 16:22:21] [INFO] [rank2]:     model = cls(config, **kwargs)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 511, in wrapper
[2025-02-10 16:22:21] [INFO] [rank2]:     f(module, *args, **kwargs)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 946, in __init__
[2025-02-10 16:22:21] [INFO] [rank2]:     self.text_model = CLIPTextTransformer(config)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 511, in wrapper
[2025-02-10 16:22:21] [INFO] [rank2]:     f(module, *args, **kwargs)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 840, in __init__
[2025-02-10 16:22:21] [INFO] [rank2]:     self.embeddings = CLIPTextEmbeddings(config)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 511, in wrapper
[2025-02-10 16:22:21] [INFO] [rank2]:     f(module, *args, **kwargs)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 205, in __init__
[2025-02-10 16:22:21] [INFO] [rank2]:     self.token_embedding = nn.Embedding(config.vocab_size, embed_dim)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 521, in wrapper
[2025-02-10 16:22:21] [INFO] [rank2]:     self._post_init_method(module)
[2025-02-10 16:22:21] [INFO] [rank2]:   File "/data/miniconda3/envs/fluxgym/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1095, in _post_init_method
[2025-02-10 16:22:21] [INFO] [rank2]:     param.data = param.data.to(self.local_device)
[2025-02-10 16:22:21] [INFO] [rank2]: NotImplementedError: Cannot copy out of meta tensor; no data!
