### ISSUE TITLE
Command exited with code 1

### ISSUE THREAD

**Issue by Telllinex** [cocktailpeanut/fluxgym#37]
Maybe because it`s forced to use bf16 which is not supported by rtx20xx arch cards?
I have 16gb ram and 12gb vram and 1/2 of Quadro 6000(Turing Generation)

[2024-09-09 13:36:15] [INFO] Traceback (most recent call last):
[2024-09-09 13:36:15] [INFO] File "D:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
[2024-09-09 13:36:15] [INFO] return _run_code(code, main_globals, None,
[2024-09-09 13:36:15] [INFO] File "D:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
[2024-09-09 13:36:15] [INFO] exec(code, run_globals)
[2024-09-09 13:36:15] [INFO] File "D:\pinokio\api\fluxgym.git\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-09 13:36:15] [INFO] File "D:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-09 13:36:15] [INFO] args.func(args)
[2024-09-09 13:36:15] [INFO] File "D:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-09 13:36:15] [INFO] simple_launcher(args)
[2024-09-09 13:36:15] [INFO] File "D:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-09 13:36:15] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-09 13:36:15] [INFO] subprocess.CalledProcessError: Command '['D:\\pinokio\\api\\fluxgym.git\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'D:\\pinokio\\api\\fluxgym.git\\models\\unet\\flux1-dev.sft', '--clip_l', 'D:\\pinokio\\api\\fluxgym.git\\models\\clip\\clip_l.safetensors', '--t5xxl', 'D:\\pinokio\\api\\fluxgym.git\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'D:\\pinokio\\api\\fluxgym.git\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'D:\\pinokio\\api\\fluxgym.git\\dataset.toml', '--output_dir', 'D:\\pinokio\\api\\fluxgym.git\\outputs', '--output_name', 'natalyn', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 3221225477.
[2024-09-09 13:36:16] [ERROR] Command exited with code 1
[2024-09-09 13:36:16] [INFO] Runner: <LogsViewRunner nb_logs=107 exit_code=1>

**Comment by Telllinex** [comment]
Idk if author of fluxgym can really do anything about this error, i tried kohyass gui and the same error occurs…. 
I saw a lot of people complaining about kohyass broken repo with a lot of issues that only lucky ones can run it without issues :)

**Comment by richiepic** [comment]
In previous comment I've seen there is a problem with pinokio install only.  Now I'm updating, but takes ages. It downloads the whole internet. 206 GB so far. ????

**Comment by Telllinex** [comment]
> In previous comment I've seen there is a problem with pinokio install only. Now I'm updating, but takes ages. It downloads the whole internet. 206 GB so far. ????

I rage deleted both kohya_ss and fluxgym and now successfully training in onetrainer without any issue on 12gb vram)
