### ISSUE TITLE
RuntimeError: use_libuv was requested but PyTorch was build without libuv support

### ISSUE THREAD

**Issue by afk4life** [cocktailpeanut/fluxgym#41]
[2024-09-09 19:22:14] [INFO] W0909 19:22:14.765000 96904 E:\pinokio\drive\drives\pip\torch\2.5.0.dev20240909+cu121\Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-09-09 19:22:16] [INFO] Traceback (most recent call last):
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
[2024-09-09 19:22:16] [INFO] return _run_code(code, main_globals, None,
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
[2024-09-09 19:22:16] [INFO] exec(code, run_globals)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-09 19:22:16] [INFO] args.func(args)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 1097, in launch_command
[2024-09-09 19:22:16] [INFO] multi_gpu_launcher(args)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 734, in multi_gpu_launcher
[2024-09-09 19:22:16] [INFO] distrib_run.run(args)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\run.py", line 910, in run
[2024-09-09 19:22:16] [INFO] elastic_launch(
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\launcher\api.py", line 138, in __call__
[2024-09-09 19:22:16] [INFO] return launch_agent(self._config, self._entrypoint, list(args))
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\launcher\api.py", line 260, in launch_agent
[2024-09-09 19:22:16] [INFO] result = agent.run()
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-09 19:22:16] [INFO] result = f(*args, **kwargs)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 696, in run
[2024-09-09 19:22:16] [INFO] result = self._invoke_run(role)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 849, in _invoke_run
[2024-09-09 19:22:16] [INFO] self._initialize_workers(self._worker_group)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-09 19:22:16] [INFO] result = f(*args, **kwargs)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 668, in _initialize_workers
[2024-09-09 19:22:16] [INFO] self._rendezvous(worker_group)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-09 19:22:16] [INFO] result = f(*args, **kwargs)
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 500, in _rendezvous
[2024-09-09 19:22:16] [INFO] rdzv_info = spec.rdzv_handler.next_rendezvous()
[2024-09-09 19:22:16] [INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 67, in next_rendezvous
[2024-09-09 19:22:16] [INFO] self._store = TCPStore(  # type: ignore[call-arg]
[2024-09-09 19:22:16] [INFO] RuntimeError: use_libuv was requested but PyTorch was build without libuv support
[2024-09-09 19:22:17] [ERROR] Command exited with code 1

**Comment by afk4life** [comment]
Thanks to @Morpheus on Discord, we solved this. It's specific to systems with dual GPUs. In order for the training to run on a multi-GPU system on Windows, click on the ^ after the first accelerate launch, shift-enter and add

--num_processes=1^

Before the line about mixed_precision bf16. Training should now run.

**Comment by thegrandmasterflash** [comment]
when launching this via CMD in windows, the command is "python app.py"

How do we use this "--num_processes=1^" trick exactly?

**Comment by afk4life** [comment]
Need to use "shift enter" to add it in there and make sure you get the ^

**Comment by kilerb** [comment]
This fix didn't work for me.  I put that line in and I still get that same error after it attempts to train.  Says it's done and to check the folder.  



> These instructions confused the hell out of me. To make it clearer- In the top right of the UI under the Start Training button there's the Train Script. Add the line so it looks like this:
> 
> ```
> accelerate launch ^
>   --num_processes=1 ^
>   --mixed_precision bf16 ^
> ```

**Comment by afk4life** [comment]
Okay what are your specs? What are you trying to train it on. It. Took 13
hours on my 4060. TI

**Comment by kilerb** [comment]
> Okay what are your specs? What are you trying to train it on. It. Took 13 hours on my 4060. TI
> […](#)
> On Sun, Sep 15, 2024, 18:02 kilerb ***@***.***> wrote: This fix didn't work for me. I put that line in and I still get that same error after it attempts to train. Says it's done and to check the folder. These instructions confused the hell out of me. To make it clearer- In the top right of the UI under the Start Training button there's the Train Script. Add the line so it looks like this: accelerate launch ^ --num_processes=1 ^ --mixed_precision bf16 ^ — Reply to this email directly, view it on GitHub <http://click.dexterous.io/ls/click?upn=u001.vABqkSU068yVqUiKjBYsS3pSCF-2BW8ZwwtUTETxkHMDNmOw69ibaXETuUyYmMlyOtqJKE4Zw6hHp5RZ6pCV5CsHTXDbaWNRTep72h4FAFuRxwaW7wklOabeH-2BTAgFECAlXCBp_51r8jo3L-2BhAoYVmO4X6H11vD3ptXn302fSdSir9r15pzKjiuhTE-2FlpTG5A-2FS-2FERx4P95Nv10Zd5FipENAunLeIo-2BiKkC4qOWq-2BjO9FrSGOcYN8vjUDim2iINlhqdFGU38L0o-2BgB5nGL9BqzJMosyzUEr-2BeqbFeHOFEjzYuO0AGBBjwYE-2BoGb4MiqLLFiHFPl0-2B-2FBHgjXkZDPY-2BwK1I7yLb53VligF7d-2B3flCjTRX086aKEdJWL9G7sB3y-2Bi9Un9b6XUBG9-2FsXL0Hnk659-2Fq-2FHg-3D-3D>, or unsubscribe <http://click.dexterous.io/ls/click?upn=u001.vABqkSU068yVqUiKjBYsS8lmWPO6P2wEPwxkZM-2FxGoHlLVsK7U9kRloKUAC5YOhHfMglzB1flZRUSnAHfCPLs-2FcloJoStksNcR3DEd7R3JoUO30rr75jTCUWmLBk6XTFz5wyZctcwLlShTijGIAvwbqkxhYQ8SrKF9evZ1-2BaAh38h2B-2Bw7Mr61DasO7p3DxlBzKAUsD2PEgu3Nm03o-2BY6ONfeHnA8M47QWJuiarZkag-3Dlule_51r8jo3L-2BhAoYVmO4X6H11vD3ptXn302fSdSir9r15pzKjiuhTE-2FlpTG5A-2FS-2FERx4P95Nv10Zd5FipENAunLeIo-2BiKkC4qOWq-2BjO9FrSGOcYN8vjUDim2iINlhqdFGU3EmsplndmhbsI05TYdv-2FMZq-2F7mIE63VcnNo9ksiVWPZkgskeRfrN-2Fj8IK1mctPGjQO7t-2FH6AhwV-2Fv6xdfCrXVYI0u5daVThbXuC-2B6glO1HZnBCKLBZiZ-2FgJi4UI0wlxPlYdhlHkf8NJL4wvCXaVl-2FMA-3D-3D> . You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Thanks...  I'm using a really beefy system.  Nvidia A6000 GPU with 48GB.  Also has an Nvidia Titan 24GB GPU.  128GB RAM etc...  It just thinks it's done training after it loads a bit...  But it's not.  Here's the train log if it helps at all....

`[2024-09-15 15:02:53] [INFO] Running D:\fluxgym\train.bat
[2024-09-15 15:02:53] [INFO] 
[2024-09-15 15:02:53] [INFO] (env) D:\fluxgym>accelerate launch --num_processes=0   --mixed_precision bf16   --num_cpu_threads_per_process 1   sd-scripts/flux_train_network.py   --pretrained_model_name_or_path "D:\fluxgym\models\unet\flux1-dev.sft"   --clip_l "D:\fluxgym\models\clip\clip_l.safetensors"   --t5xxl "D:\fluxgym\models\clip\t5xxl_fp16.safetensors"   --ae "D:\fluxgym\models\vae\ae.sft"   --cache_latents_to_disk   --save_model_as safetensors   --sdpa --persistent_data_loader_workers   --max_data_loader_n_workers 2   --seed 42   --gradient_checkpointing   --mixed_precision bf16   --save_precision bf16   --network_module networks.lora_flux   --network_dim 4   --optimizer_type adamw8bit   --learning_rate 8e-4   --cache_text_encoder_outputs   --cache_text_encoder_outputs_to_disk   --fp8_base   --highvram   --max_train_epochs 16   --save_every_n_epochs 4   --dataset_config "D:\fluxgym\dataset.toml"   --output_dir "D:\fluxgym\outputs"   --output_name david-spade   --timestep_sampling shift   --discrete_flow_shift 3.1582   --model_prediction_type raw   --guidance_scale 1   --loss_type l2
[2024-09-15 15:02:57] [INFO] W0915 15:02:57.908737 25284 Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-09-15 15:03:00] [INFO] Traceback (most recent call last):
[2024-09-15 15:03:00] [INFO] File "C:\Users\Brian\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
[2024-09-15 15:03:00] [INFO] return _run_code(code, main_globals, None,
[2024-09-15 15:03:00] [INFO] File "C:\Users\Brian\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
[2024-09-15 15:03:00] [INFO] exec(code, run_globals)
[2024-09-15 15:03:00] [INFO] File "D:\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-15 15:03:00] [INFO] File "D:\fluxgym\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-15 15:03:00] [INFO] args.func(args)
[2024-09-15 15:03:00] [INFO] File "D:\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 1097, in launch_command
[2024-09-15 15:03:00] [INFO] multi_gpu_launcher(args)
[2024-09-15 15:03:00] [INFO] File "D:\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 734, in multi_gpu_launcher
[2024-09-15 15:03:00] [INFO] distrib_run.run(args)
[2024-09-15 15:03:00] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\run.py", line 910, in run
[2024-09-15 15:03:00] [INFO] elastic_launch(
[2024-09-15 15:03:00] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\launcher\api.py", line 138, in __call__
[2024-09-15 15:03:00] [INFO] return launch_agent(self._config, self._entrypoint, list(args))
[2024-09-15 15:03:00] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\launcher\api.py", line 236, in launch_agent
[2024-09-15 15:03:00] [INFO] spec = WorkerSpec(
[2024-09-15 15:03:00] [INFO] File "<string>", line 14, in __init__
[2024-09-15 15:03:00] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 91, in __post_init__
[2024-09-15 15:03:00] [INFO] assert self.local_world_size > 0
[2024-09-15 15:03:00] [INFO] AssertionError
[2024-09-15 15:03:00] [ERROR] Command exited with code 1
[2024-09-15 15:03:00] [INFO] Runner: <LogsViewRunner nb_logs=27 exit_code=1>`

**Comment by afk4life** [comment]
I'm prolly gonna get banned for this but it you have a 48G with a ton of RAM,  card use AI Toolikt. Not this, this is great for us who are VRAM deprived.  Git clone it, git clone the dev Flux which needs API key and will take a long time to download, then train. My email is doug at hardwick.xyz if you need help. Cheers...

**Comment by Single-Sin** [comment]
Halo, I have two A5000 GPU, I also can't start the training too...how can I fix it problem??

**Comment by afk4life** [comment]
Just edit the command prompt at the right as specified.

**Comment by arastouart** [comment]
i have same problem, i find when i'm using !wget command in jupiter notebook for download models on cloud servers, that file downloaded from hugging face, named "flux-dev.safetensors?download" , you should renamed that to "flux-dev.safetensors" for working well. also for clip models and vae.

**Comment by UUDaddy369** [comment]
After I press shift+Enter, and paste 

accelerate launch ^
  --num_processes=1 ^
  --mixed_precision bf16 ^
 
 Then, the "Train Script" AUTO refresh to default ! 
 
 accelerate launch ^
  --mixed_precision bf16 ^
  --num_cpu_threads_per_process 1 ^

Why? Does anybody know? Many thanks.
My Spec. RTX 3060 12G

**Comment by postmrtm** [comment]
same here, auto refreshes and doesnt save my changes
anyone solved this?

**Comment by ThisModernDay** [comment]
Just +1 that the script section autorefreshes when you edit it and reverts back to the default for me as well

**Comment by ThisModernDay** [comment]
@postmrtm @UUDaddy369 @afk4life 

for now if you edit the app.py file and modify the code here
which starts at line `453`

```Python
 sh = f"""accelerate launch {line_break}
  --num_processes=1^ {line_break}
  --mixed_precision bf16 {line_break}
  ```

**Comment by vlegacy** [comment]
@afk4life on which discord server you're communicating?

**Comment by hiyazakite** [comment]
For me there was a conflict with my global accelerate install which was confusing me, worth a try. You don't need to change app.py or num_processes if you disable multi gpu using accelerate config

**Comment by ferrariboy** [comment]
> For me there was a conflict with my global accelerate install which was confusing me, worth a try. You don't need to change app.py or num_processes if you disable multi gpu using accelerate config

So did you manage to get it working? I have an older laptop with integrated Intel graphics card and an Nvidia GTX 1050.
1) Will it be able to run Fluxgym?
2) How have you disabled multi-GPU and configure it to use the Nvidia GPU?

Thanks for any advice. I know my system is so old... :(

**Comment by ferrariboy** [comment]
I've re-installed everything twice.

Still "completes" training in 3 seconds....
Error code "accelerate <command> [<args>] launch: error: the following arguments are required: training_script, training_script_args"
I did not touch anything, so I don't know what's wrong or if the training scripts have not been properly downloaded.... I give up, spent 4 hours on this already.

**Comment by hiyazakite** [comment]
You won't have any luck with a 1050 as you need minimum of 12GB VRAM for training. My advice to you would to spin up a cloud gpu instance on runpod or vast or the likes. I have 2 x 3090 and my problem was that accelerate was still using multi-gpu settings even though num_processes was hardcoded to 1. By executing accelerate config in terminal (you just answer yes/no questions
, similar to an init script) and disabling the use of one of my gpu's i was able to proceed with training.

**Comment by cigncloud** [comment]
⏭️ **Skipping Model Management Scripts** - User requested to skip detailed model management implementation and proceed with core environment setup.
