### ISSUE TITLE
Caption not working 

### ISSUE THREAD

**Issue by Dartsgame974** [cocktailpeanut/fluxgym#70]
Hello , I try on Pinokio and manually install FLux Gym, but on in the noth ways I have issues with Captionning 

I try to change device put nothing working its still on "cpu" 
I install Cuda twice time, that not fix the issue

I don't know why that said me the model of Florence is use by other program, so that's totally wrong !

Why that not complete download the model?

The download looks crashing a moment : That is the logs

`C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
pytorch_model.bin:  31%|██████████████████▊                                         | 484M/1.54G [10:51<23:45, 743kB/s]
Traceback (most recent call last):
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 523, in http_get
    hf_transfer.download(
Exception: Error while removing corrupted file: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. (os error 32)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 3280, in from_pretrained
    resolved_archive_file = cached_file(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\hub.py", line 389, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1389, in _hf_hub_download_to_cache_dir
    _download_to_tmp_and_move(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1916, in _download_to_tmp_and_move
    http_get(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 534, in http_get
    raise RuntimeError(
RuntimeError: An error occurred while downloading using `hf_transfer`. Consider disabling HF_HUB_ENABLE_HF_TRANSFER for better error handling.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 809, in gen_wrapper
    response = next(iterator)
  File "C:\Users\DartsgameKZ\Downloads\Ai\fluxgym\app.py", line 118, in run_captioning
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\DartsgameKZ\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 3332, in from_pretrained
    raise EnvironmentError(
OSError: Can't load the model for 'multimodalart/Florence-2-large-no-flash-attn'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'multimodalart/Florence-2-large-no-flash-attn' is the correct path to a directory containing a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.

`

**Comment by max-k54** [comment]
Facing the same issue, have you found a solution yet?

**Comment by arcs002** [comment]
same here, i tried to label the images outside fluxgym to go straigh to the trainning, but the trainning also runs on CPU i have a 3060

**Comment by arcs002** [comment]
after digging around i found out that the pytorch was installed without cuda support, not sure why....
to fix this the workaround i did was to force the installation of the right version of pytorch, i changed the file update.js to be something like this:

`module.exports = {
  run: [  {
    method: "shell.run",
    params: {
      venv: "env",
      message: [
        "pip uninstall -y diffusers[torch] torch torchaudio torchvision",
        "pip install --pre torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/cu121"        
      ]
    }
  }, {
    method: "fs.link",
    params: {
      venv: "env"
    }
  }]
}
`

After that i run the update and everything seems to be working fine.

PS: This is just a workaround, if you try to do it, dont forget to rollback the update.js to the original content, so you can update it later if needed.

**Comment by dominion2** [comment]
> after digging around i found out that the pytorch was installed without cuda support, not sure why.... to fix this the workaround i did was to force the installation of the right version of pytorch, i changed the file update.js to be something like this:
> 
> `module.exports = { run: [ { method: "shell.run", params: { venv: "env", message: [ "pip uninstall -y diffusers[torch] torch torchaudio torchvision", "pip install --pre torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/cu121" ] } }, { method: "fs.link", params: { venv: "env" } }] } `
> 
> After that i run the update and everything seems to be working fine.
> 
> PS: This is just a workaround, if you try to do it, dont forget to rollback the update.js to the original content, so you can update it later if needed.

------------------------

Thank you for the feedback.  It seems like I got it working I updated update.js with my latest version of CUDA with just changing the following lines:

{
    method: "shell.run",
    params: {
      venv: "env",
      message: [
        "pip uninstall -y diffusers[torch] torch torchaudio torchvision", "pip install --pre torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl
	/cu126"
      ]
    }

then I ran node update.js.  I did do a pip install -r requirements.txt again but I had to reload my NVIDIA drivers.  I felt like it was more trial then error to get it working but this message is finally gone: 

"UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0"

**Comment by Hoyaaa1** [comment]
I downloaded the model manually and pasted it into the cache directory, then connected to high-speed internet and waited for it to complete.

Cache directory: Local: C:\Users\%USERNAME%\.cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\blobs Or in Pinokio, in the fluxgym folder and cache folder.

**Comment by KLL535** [comment]
> I downloaded the model manually and pasted it into the cache directory, then connected to high-speed internet and waited for it to complete.
> 
> Cache directory: Local: C:\Users%USERNAME%.cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\blobs Or in Pinokio, in the fluxgym folder and cache folder.

How did you do it?
I don't have such a path. I don't understand where to put the file so that it stops downloading again.

**Comment by KLL535** [comment]
Anyone who has everything working, take a look where this file is located in the end? Or does it not work for anyone? Or in what file do I need to change something to DISABLE THIS ENDLESS LOADING?

pytorch_model.bin:  98%|█████████████████████████████████████████████████████████▊ | 1.51G/1.54G [10:55<02:43, 193kB/s]

**Comment by Robcis** [comment]
This is how I solved it. It might not work for everyone but it worked for me.

# Fix for Florence Model Download Issues

This fixes the constant model redownload issues and missing models.yaml errors. Make these changes in `app.py`:

1. Around line 26 (after all imports and `MAX_IMAGES = 150`), replace:
```python
with open('models.yaml', 'r') as file:
    models = yaml.safe_load(file)
```

with:
```python
models = {}
try:
    with open('models.yaml', 'r') as file:
        models = yaml.safe_load(file)
except FileNotFoundError:
    # Create a default models.yaml
    default_models = {
        "flux-dev": {
            "file": "model.safetensors",
            "repo": "cocktailpeanut/flux-dev",
            "base": "flux-dev"
        }
    }
    with open('models.yaml', 'w') as file:
        yaml.dump(default_models, file)
    models = default_models
```

2. At the very top of app.py (first lines), add:
```python
import os
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "0"  # Disable HF transfer
os.environ['TRANSFORMERS_CACHE'] = os.path.join(os.getcwd(), "cache")
os.environ['HF_HOME'] = os.path.join(os.getcwd(), "cache")
```

These changes ensure the app works without models.yaml and properly caches downloaded models.

**Comment by musama-khalid** [comment]
> This is how I solved it. It might not work for everyone but it worked for me.
> 
> # Fix for Florence Model Download Issues
> This fixes the constant model redownload issues and missing models.yaml errors. Make these changes in `app.py` within the FluxGym directory:
> 
> 1. Around line 26 (after all imports and `MAX_IMAGES = 150`), replace:
> 
> with open('models.yaml', 'r') as file:
>     models = yaml.safe_load(file)
> with:
> 
> models = {}
> try:
>     with open('models.yaml', 'r') as file:
>         models = yaml.safe_load(file)
> except FileNotFoundError:
>     # Create a default models.yaml
>     default_models = {
>         "flux-dev": {
>             "file": "model.safetensors",
>             "repo": "cocktailpeanut/flux-dev",
>             "base": "flux-dev"
>         }
>     }
>     with open('models.yaml', 'w') as file:
>         yaml.dump(default_models, file)
>     models = default_models
> 2. At the very top of app.py (first lines), add:
> 
> import os
> os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "0"  # Disable HF transfer
> os.environ['TRANSFORMERS_CACHE'] = os.path.join(os.getcwd(), "cache")
> os.environ['HF_HOME'] = os.path.join(os.getcwd(), "cache")
> These changes ensure the app works without models.yaml and properly caches downloaded models.

Thank you, it worked for me.

**Comment by mahan100** [comment]
directory path for manual downloading of florence-2 is:


C:\pinokio\api\fluxgym.git\cache\models--multimodalart--Florence-2-large-no-flash-attn\snapshots\8db3793cf5b453b2ccfb3a4f613b403b2e6b7ca2\


its obvious the last directory <8db3793cf5b453b2ccfb3a4f613b403b2e6b7ca2> has different  name for you
