### ISSUE TITLE
Flug Gym says it's done training after 10 seconds

### ISSUE THREAD

**Issue by kilerb** [cocktailpeanut/fluxgym#74]
Hi...  I got it working and added my images and had it add captions.  I hit "start training" and after about 10 seconds it says "Training Complete. Check the outputs folder for the LoRA files."  Which is obviously way too fast and there's nothing there.  Any idea why it thinks it's done when it didn't do anything?  I kept all the settings at default and I have a beefy NVidia A6000 card with 48GB VRam.  Thanks!

**Comment by sabutay** [comment]
same problem

**Comment by ILikeToasters** [comment]
Answered here: https://github.com/cocktailpeanut/fluxgym/issues/41

**Comment by kilerb** [comment]
> Answered here: #41

I added that text right where it said to.  I put Still says done with training after 20 seconds or so.  I restarted the entire program and tried again.  Same thing.  Not working.  

Iadded the num processes line just like this...

accelerate launch ^
  --num_processes=1 ^
  --mixed_precision bf16 ^

Here's the train log if it helps... 
 
`[2024-09-15 14:56:07] [INFO] Running D:\fluxgym\train.bat
[2024-09-15 14:56:07] [INFO] 
[2024-09-15 14:56:07] [INFO] (env) D:\fluxgym>accelerate launch --num_processes=1   --mixed_precision bf16   --num_cpu_threads_per_process 1   sd-scripts/flux_train_network.py   --pretrained_model_name_or_path "D:\fluxgym\models\unet\flux1-dev.sft"   --clip_l "D:\fluxgym\models\clip\clip_l.safetensors"   --t5xxl "D:\fluxgym\models\clip\t5xxl_fp16.safetensors"   --ae "D:\fluxgym\models\vae\ae.sft"   --cache_latents_to_disk   --save_model_as safetensors   --sdpa --persistent_data_loader_workers   --max_data_loader_n_workers 2   --seed 42   --gradient_checkpointing   --mixed_precision bf16   --save_precision bf16   --network_module networks.lora_flux   --network_dim 4   --optimizer_type adamw8bit   --learning_rate 8e-4   --cache_text_encoder_outputs   --cache_text_encoder_outputs_to_disk   --fp8_base   --highvram   --max_train_epochs 16   --save_every_n_epochs 4   --dataset_config "D:\fluxgym\dataset.toml"   --output_dir "D:\fluxgym\outputs"   --output_name david-spade   --timestep_sampling shift   --discrete_flow_shift 3.1582   --model_prediction_type raw   --guidance_scale 1   --loss_type l2
[2024-09-15 14:56:11] [INFO] W0915 14:56:11.621557 21000 Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-09-15 14:56:13] [INFO] Traceback (most recent call last):
[2024-09-15 14:56:13] [INFO] File "C:\Users\Brian\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
[2024-09-15 14:56:13] [INFO] return _run_code(code, main_globals, None,
[2024-09-15 14:56:13] [INFO] File "C:\Users\Brian\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
[2024-09-15 14:56:13] [INFO] exec(code, run_globals)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-15 14:56:13] [INFO] args.func(args)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 1097, in launch_command
[2024-09-15 14:56:13] [INFO] multi_gpu_launcher(args)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 734, in multi_gpu_launcher
[2024-09-15 14:56:13] [INFO] distrib_run.run(args)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\run.py", line 910, in run
[2024-09-15 14:56:13] [INFO] elastic_launch(
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\launcher\api.py", line 138, in __call__
[2024-09-15 14:56:13] [INFO] return launch_agent(self._config, self._entrypoint, list(args))
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\launcher\api.py", line 260, in launch_agent
[2024-09-15 14:56:13] [INFO] result = agent.run()
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-15 14:56:13] [INFO] result = f(*args, **kwargs)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 696, in run
[2024-09-15 14:56:13] [INFO] result = self._invoke_run(role)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 849, in _invoke_run
[2024-09-15 14:56:13] [INFO] self._initialize_workers(self._worker_group)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-15 14:56:13] [INFO] result = f(*args, **kwargs)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 668, in _initialize_workers
[2024-09-15 14:56:13] [INFO] self._rendezvous(worker_group)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-15 14:56:13] [INFO] result = f(*args, **kwargs)
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 500, in _rendezvous
[2024-09-15 14:56:13] [INFO] rdzv_info = spec.rdzv_handler.next_rendezvous()
[2024-09-15 14:56:13] [INFO] File "D:\fluxgym\env\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 67, in next_rendezvous
[2024-09-15 14:56:13] [INFO] self._store = TCPStore(  # type: ignore[call-arg]
[2024-09-15 14:56:13] [INFO] RuntimeError: use_libuv was requested but PyTorch was build without libuv support
[2024-09-15 14:56:14] [ERROR] Command exited with code 1
[2024-09-15 14:56:14] [INFO] Runner: <LogsViewRunner nb_logs=40 exit_code=1>`

**Comment by arastouart** [comment]
i have same problem, i find when i'm using !wget command in jupiter notebook for download models on cloud servers, that file downloaded from hugging face, named "flux-dev.safetensors?download" , you should renamed that to "flux-dev.safetensors" for working well. also for clip models and vae.

**Comment by IckeBins67** [comment]
No chance! Same Problem. Finished after few seconds.

**Comment by tangyuming99** [comment]
The model was not downloaded
