### ISSUE TITLE
Process error: command returned non-zero exit status 3221225477

### ISSUE THREAD

**Issue by scheseb** [cocktailpeanut/fluxgym#78]
Hi everyone,

the following error consistently appears a few seconds after having started the training.
Settings are set to default and using 12G of VRAM.

My main specs:
Windows 11
AMD Ryzen 7 5800X
Geforce RTX 3060 with 12GB GDDR6

Any ideas what could be wrong? I couldn't find anything meaningful in pinokio's "logs" folder either.

Thank you!

`[2024-09-15 09:19:15] [INFO] Traceback (most recent call last):
[2024-09-15 09:19:15] [INFO] File "C:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
[2024-09-15 09:19:15] [INFO] return _run_code(code, main_globals, None,
[2024-09-15 09:19:15] [INFO] File "C:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
[2024-09-15 09:19:15] [INFO] exec(code, run_globals)
[2024-09-15 09:19:15] [INFO] File "C:\pinokio\api\fluxgym.git\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-15 09:19:15] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-15 09:19:15] [INFO] args.func(args)
[2024-09-15 09:19:15] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-15 09:19:15] [INFO] simple_launcher(args)
[2024-09-15 09:19:15] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-15 09:19:15] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-15 09:19:15] [INFO] subprocess.CalledProcessError: Command '['C:\\pinokio\\api\\fluxgym.git\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'C:\\pinokio\\api\\fluxgym.git\\models\\unet\\flux1-dev.sft', '--clip_l', 'C:\\pinokio\\api\\fluxgym.git\\models\\clip\\clip_l.safetensors', '--t5xxl', 'C:\\pinokio\\api\\fluxgym.git\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'C:\\pinokio\\api\\fluxgym.git\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'C:\\pinokio\\api\\fluxgym.git\\dataset.toml', '--output_dir', 'C:\\pinokio\\api\\fluxgym.git\\outputs', '--output_name', 'sternenstaub', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 3221225477.
[2024-09-15 09:19:15] [ERROR] Command exited with code 1
[2024-09-15 09:19:15] [INFO] Runner: <LogsViewRunner nb_logs=110 exit_code=1>`

**Comment by Telllinex** [comment]
No fix rn, it`s a kohya_ss scripts fault, try using kohya_ss gui and its 41afd2662ff11e70630066bfbc6101a3272420ab or f066bfd commit (haven't tried f066bfd but it's from reddit reported to be working) 
Also check your pagefile size(i have 37 gb and still have to reboot after training)

**Comment by scheseb** [comment]
Thanks for your reply, @Telllinex .

This error is gone now after updating fluxgym to latest version and increasing my pagefile size from 32GB to 40GB. I didn't test changes individually, so I don't know what fixed it.

However, now I am getting an OOM error:

```
[2024-09-18 08:19:50] [INFO] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 80.00 MiB. GPU 0 has a total capacity of 12.00 GiB of which 6.31 GiB is free. Of the allocated memory 4.64 GiB is allocated by PyTorch, and 14.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-09-18 08:19:51] [INFO] Traceback (most recent call last):
[2024-09-18 08:19:51] [INFO] File "C:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
[2024-09-18 08:19:51] [INFO] return _run_code(code, main_globals, None,
[2024-09-18 08:19:51] [INFO] File "C:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
[2024-09-18 08:19:51] [INFO] exec(code, run_globals)
[2024-09-18 08:19:51] [INFO] File "C:\pinokio\api\fluxgym.git\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-18 08:19:51] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-18 08:19:51] [INFO] args.func(args)
[2024-09-18 08:19:51] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-18 08:19:51] [INFO] simple_launcher(args)
[2024-09-18 08:19:51] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-18 08:19:51] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-18 08:19:51] [INFO] subprocess.CalledProcessError: Command '['C:\\pinokio\\api\\fluxgym.git\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'C:\\pinokio\\api\\fluxgym.git\\models\\unet\\flux1-dev.sft', '--clip_l', 'C:\\pinokio\\api\\fluxgym.git\\models\\clip\\clip_l.safetensors', '--t5xxl', 'C:\\pinokio\\api\\fluxgym.git\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'C:\\pinokio\\api\\fluxgym.git\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '10', '--save_every_n_epochs', '4', '--dataset_config', 'C:\\pinokio\\api\\fluxgym.git\\outputs\\sternenstaub\\dataset.toml', '--output_dir', 'C:\\pinokio\\api\\fluxgym.git\\outputs\\sternenstaub', '--output_name', 'sternenstaub', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-09-18 08:19:51] [ERROR] Command exited with code 1
```

**Comment by Telllinex** [comment]
I migrated to OneTrainer and using config from Reddit post, it successfully works without any issues)

**Comment by scheseb** [comment]
I'll close this then as the original error is gone.
The OOM error is a separate issue.
