### ISSUE TITLE
florence-2 no internet. no working?

### ISSUE THREAD

**Issue by xxl2005** [cocktailpeanut/fluxgym#81]
florence-2 needs internet connection to work even though the model is 100% downloaded?. can you fix it so that it works offline too

`run_captioning
concept sentence bh3a
captions ('bh3a', 'bh3a', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '')
device=cuda
Traceback (most recent call last):
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/tobias/miniconda3/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7c7e00bd3010>: Failed to resolve 'huggingface.co' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /multimodalart/Florence-2-large-no-flash-attn/resolve/main/model.safetensors (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c7e00bd3010>: Failed to resolve 'huggingface.co' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/gradio/blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/gradio/utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/gradio/utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/gradio/utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/gradio/utils.py", line 809, in gen_wrapper
    response = next(iterator)
  File "/home/tobias/AI/fluxgym/app.py", line 118, in run_captioning
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 559, in from_pretrained
    return model_class.from_pretrained(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3594, in from_pretrained
    if not has_file(pretrained_model_name_or_path, safe_weights_name, **has_file_kwargs):
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 655, in has_file
    response = get_session().head(
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/requests/sessions.py", line 624, in head
    return self.request("HEAD", url, **kwargs)
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "/home/tobias/AI/fluxgym/env/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /multimodalart/Florence-2-large-no-flash-attn/resolve/main/model.safetensors (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c7e00bd3010>: Failed to resolve \'huggingface.co\' ([Errno -2] Name or service not known)"))'), '(Request ID: af4d896c-0211-410d-a82e-2691bf94a3a2)')

`

**Comment by CastawayEGR** [comment]
Try setting the following environment variable.
`HF_HUB_OFFLINE=1`

**Comment by Hoyaaa1** [comment]
I downloaded the model manually and pasted it into the cache directory, then connected to high-speed internet and waited for it to complete.

Cache directory: Local: C:\Users\%USERNAME%\.cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\blobs Or in Pinokio, in the fluxgym folder and cache folder.

**Comment by KLL535** [comment]
> I downloaded the model manually 
Where can I download the model manually?

This line never ends:

pytorch_model.bin:   0%|                                                                                                   | 0.00/1.54G [00:00<?, ?B/s]

Linux-like is a very bad system, since everything is tied to the Internet.

**Comment by KLL535** [comment]
Progress?

 pytorch_model.bin:   4%|██▎                                                       | 62.9M/1.54G [01:19<15:15, 1.62MB/s]

Downloaded to 4% and froze. What's wrong with this file or this CODE and how to fix it? Where can I download this file MANUALLY?

Everything else is downloaded somehow.
