### ISSUE TITLE
RuntimeError: use_libuv was requested but PyTorch was build without libuv support

### ISSUE THREAD

**Issue by evelryu** [cocktailpeanut/fluxgym#82]
39] [INFO] rdzv_info = spec.dzv_handler.next_rendezvous()
39] [
INFO] File "E:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\rendez
39] [INFO] self._store = TCPStore (# type: ignore [call-arg]
39] [INFO] RuntimeError: use_libuv was requested but PyTorch was build without libuv support
41] [ERROR] Command exited with code 1
41] [INFO] Runner: <LogsViewRunner nb_logs

**Comment by evelryu** [comment]
Anyway to fix this?

**Comment by ReinhardKepplinger** [comment]
hope it's ok to post here got samer error i guess - could it be problem of multi gpu setup?

i have 3 GPU 1 2060 6GB for monitor and 2x 2080ti 11GB or maybe 11GB is the issue?
tried to reinstall few times btw
and selected workre 1 2060 should be disabled for cuda in nvidia control panel

should i make a new thread or its ok to post here?

thanks in advance

[2024-09-15 13:06:08] [INFO] Running f:\pinokio\api\fluxgym.git\train.bat
[2024-09-15 13:06:08] [INFO] 
[2024-09-15 13:06:08] [INFO] (env) (base) f:\pinokio\api\fluxgym.git>accelerate launch   --mixed_precision bf16   --num_cpu_threads_per_process 1   sd-scripts/flux_train_network.py   --pretrained_model_name_or_path "f:\pinokio\api\fluxgym.git\models\unet\flux1-dev.sft"   --clip_l "f:\pinokio\api\fluxgym.git\models\clip\clip_l.safetensors"   --t5xxl "f:\pinokio\api\fluxgym.git\models\clip\t5xxl_fp16.safetensors"   --ae "f:\pinokio\api\fluxgym.git\models\vae\ae.sft"   --cache_latents_to_disk   --save_model_as safetensors   --sdpa --persistent_data_loader_workers   --max_data_loader_n_workers 1   --seed 42   --gradient_checkpointing   --mixed_precision bf16   --save_precision bf16   --network_module networks.lora_flux   --network_dim 4   --optimizer_type adafactor   --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False"   --split_mode   --network_args "train_blocks=single"   --lr_scheduler constant_with_warmup   --max_grad_norm 0.0 --sample_prompts="f:\pinokio\api\fluxgym.git\sample_prompts.txt" --sample_every_n_steps="50"   --learning_rate 8e-4   --cache_text_encoder_outputs   --cache_text_encoder_outputs_to_disk   --fp8_base   --highvram   --max_train_epochs 13   --save_every_n_epochs 2   --dataset_config "f:\pinokio\api\fluxgym.git\dataset.toml"   --output_dir "f:\pinokio\api\fluxgym.git\outputs"   --output_name hofbauermv1-woman   --timestep_sampling shift   --discrete_flow_shift 3.1582   --model_prediction_type raw   --guidance_scale 1   --loss_type l2
[2024-09-15 13:06:16] [INFO] The following values were not passed to `accelerate launch` and had defaults used instead:
[2024-09-15 13:06:16] [INFO] `--num_processes` was set to a value of `2`
[2024-09-15 13:06:16] [INFO] More than one GPU was found, enabling multi-GPU training.
[2024-09-15 13:06:16] [INFO] If this was unintended please pass in `--num_processes=1`.
[2024-09-15 13:06:16] [INFO] `--num_machines` was set to a value of `1`
[2024-09-15 13:06:16] [INFO] `--dynamo_backend` was set to a value of `'no'`
[2024-09-15 13:06:16] [INFO] To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-09-15 13:06:16] [INFO] W0915 13:06:16.569000 41056 F:\pinokio\drive\drives\pip\torch\2.5.0.dev20240911+cu121\Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-09-15 13:06:18] [INFO] Traceback (most recent call last):
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
[2024-09-15 13:06:18] [INFO] return _run_code(code, main_globals, None,
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
[2024-09-15 13:06:18] [INFO] exec(code, run_globals)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-15 13:06:18] [INFO] args.func(args)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 1097, in launch_command
[2024-09-15 13:06:18] [INFO] multi_gpu_launcher(args)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 734, in multi_gpu_launcher
[2024-09-15 13:06:18] [INFO] distrib_run.run(args)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\run.py", line 910, in run
[2024-09-15 13:06:18] [INFO] elastic_launch(
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\launcher\api.py", line 138, in __call__
[2024-09-15 13:06:18] [INFO] return launch_agent(self._config, self._entrypoint, list(args))
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\launcher\api.py", line 260, in launch_agent
[2024-09-15 13:06:18] [INFO] result = agent.run()
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-15 13:06:18] [INFO] result = f(*args, **kwargs)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 696, in run
[2024-09-15 13:06:18] [INFO] result = self._invoke_run(role)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 849, in _invoke_run
[2024-09-15 13:06:18] [INFO] self._initialize_workers(self._worker_group)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-15 13:06:18] [INFO] result = f(*args, **kwargs)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 668, in _initialize_workers
[2024-09-15 13:06:18] [INFO] self._rendezvous(worker_group)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
[2024-09-15 13:06:18] [INFO] result = f(*args, **kwargs)
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 500, in _rendezvous
[2024-09-15 13:06:18] [INFO] rdzv_info = spec.rdzv_handler.next_rendezvous()
[2024-09-15 13:06:18] [INFO] File "f:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 67, in next_rendezvous
[2024-09-15 13:06:18] [INFO] self._store = TCPStore(  # type: ignore[call-arg]
[2024-09-15 13:06:18] [INFO] RuntimeError: use_libuv was requested but PyTorch was build without libuv support
[2024-09-15 13:06:19] [ERROR] Command exited with code 1
[2024-09-15 13:06:19] [INFO] Runner: <LogsViewRunner nb_logs=47 exit_code=1>

**Comment by kilerb** [comment]
I have the same issue and I do have 2 GPU's.  I tried it again after going to device manager and disabling one of the cards.  But it still gave the same issue.  So not sure if that's just not the right fix.  But I did notice in the train log that at line 14 it says "[2024-09-14 20:11:47] [INFO] multi_gpu_launcher(args)
[2024-09-14 20:11:47] [INFO] File "D:\fluxgym\env\lib\site-packages\accelerate\commands\launch.py", line 734, in multi_gpu_launcher"  
So maybe it does have something to do with it?  No idea.  Hopefully we can figure this out.

**Comment by ILikeToasters** [comment]
Your answer is in this previous post about that error. https://github.com/cocktailpeanut/fluxgym/issues/41
