### ISSUE TITLE
This error has occurred, please ask if anyone can help correct the error

### ISSUE THREAD

**Issue by wuliang19869312** [cocktailpeanut/fluxgym#86]
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "D:\pinokio\api\fluxgym\app.py", line 651, in <module>
    demo.launch(show_error=True, allowed_paths=[cwd])
  File "D:\pinokio\api\fluxgym\env\Lib\site-packages\gradio\blocks.py", line 2466, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by wuliang19869312** [comment]
Traceback (most recent call last):
  File "d:\pinokio\api\fluxgym\app.py", line 651, in <module>
    demo.launch(show_error=True, allowed_paths=[cwd])
  File "d:\pinokio\api\fluxgym\env\lib\site-packages\gradio\blocks.py", line 2466, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True o
r check your proxy settings to allow access to localhost.

**Comment by wuliang19869312** [comment]
2024-09-15T16:01:20Z ERR Failed to fetch features, default to disable error="lookup cfd-features.argot
unnel.com: dnsquery: This operation returned because the timeout period expired."
2024-09-15T16:01:32Z WRN Unable to lookup protocol percentage.
2024-09-15T16:01:32Z INF Initial protocol quic
2024-09-15T16:01:32Z INF ICMP proxy will use 192.168.1.2 as source for IPv4
2024-09-15T16:01:32Z INF ICMP proxy will use 2409:8a1e:7a25:bb90:1553:aec9:ecc6:40a0 in zone WLAN as s
ource for IPv6
2024-09-15T16:01:32Z INF cloudflared does not support loading the system root certificate pool on Wind
ows. Please use --origin-ca-pool <PATH> to specify the path to the certificate pool
2024-09-15T16:01:32Z INF Starting metrics server on 127.0.0.1:51620/metrics
2024-09-15T16:01:38Z ERR Failed to create new quic connection error="failed to dial to edge with quic:
 timeout: no recent network activity" connIndex=0 event=0 ip=198.41.200.33
2024-09-15T16:01:38Z INF Retrying connection in up to 2s connIndex=0 event=0 ip=198.41.200.33
2024-09-15T16:01:39Z INF Registered tunnel connection connIndex=0 connection=8ce0ef8e-3ef3-4dd2-b10b-f
ddb8ee67188 event=0 ip=198.41.192.67 location=sjc01 protocol=quic


 File "d:\pinokio\api\fluxgym.git\app.py", line 651, in <module>
    demo.launch(show_error=True, allowed_paths=[cwd])
  File "d:\pinokio\api\fluxgym.git\env\lib\site-packages\gradio\blocks.py", line 2466, in launch      
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True 
or check your proxy settings to allow access to localhost.

**Comment by fahadshery** [comment]
you can change the `localhost` to an actual IP address by changing `args` in the `main` method where you launch the app in the `app.py` file.
check the docker PR

**Comment by wuliang19869312** [comment]
> you can change the `localhost` to an actual IP address by changing `args` in the `main` method where you launch the app in the `app.py` file. check the docker PR

Not knowing much about the procedure, can you tell me exactly how to change it?

**Comment by one-pip** [comment]
try close the VPN

**Comment by starbuck100** [comment]
@wuliang19869312  

Head to fluxgym/app.py and edit the last lines like following:

if __name__ == "__main__":
    cwd = os.path.dirname(os.path.abspath(__file__))
    demo.launch(show_error=True, allowed_paths=[cwd], server_name="0.0.0.0")
    

This will share the gradio interface trough your local network.
