### ISSUE TITLE
deepspeed was missing, then torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by byteconcepts** [cocktailpeanut/fluxgym#87]
Followed the manual installation process on Ubuntu Linux 4090 24G.

On the first run I got the error message that the deepspeed package was missing -> installed it.

Next tries I got the following error messages...

```
[2024-09-15 20:18:01] [INFO] enable fp8 training for Text Encoder.
[2024-09-15 20:18:04] [INFO] 2024-09-15 20:18:04 INFO     prepare CLIP-L for fp8: set to torch.float8_e4m3fn, set embeddings to torch.bfloat16       flux_train_network.py:464
[2024-09-15 20:18:04] [INFO] [rank0]: Traceback (most recent call last):
[2024-09-15 20:18:04] [INFO] [rank0]:   File "/srv/www/vhosts/fluxgym/sd-scripts/flux_train_network.py", line 519, in <module>
[2024-09-15 20:18:04] [INFO] [rank0]:     trainer.train(args)
[2024-09-15 20:18:04] [INFO] [rank0]:   File "/srv/www/vhosts/fluxgym/sd-scripts/train_network.py", line 596, in train
[2024-09-15 20:18:04] [INFO] [rank0]:     unet = accelerator.prepare(unet)
[2024-09-15 20:18:04] [INFO] [rank0]:   File "/srv/www/vhosts/fluxgym/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1303, in prepare
[2024-09-15 20:18:04] [INFO] [rank0]:     result = self._prepare_deepspeed(*args)
[2024-09-15 20:18:04] [INFO] [rank0]:   File "/srv/www/vhosts/fluxgym/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1621, in _prepare_deepspeed
[2024-09-15 20:18:04] [INFO] [rank0]:     raise ValueError(
[2024-09-15 20:18:04] [INFO] [rank0]: ValueError: When using DeepSpeed, `accelerate.prepare()` requires you to pass at least one of training or evaluation dataloaders with `batch_size` attribute returning an integer value or alternatively set an integer value in `train_micro_batch_size_per_gpu` in the deepspeed config file or assign integer value to `AcceleratorState().deepspeed_plugin.deepspeed_config['train_micro_batch_size_per_gpu']`.
[2024-09-15 20:18:04] [INFO] [rank0]:[W915 20:18:04.860252397 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[2024-09-15 20:18:05] [INFO] E0915 20:18:05.670000 5825 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 5881) of binary: /srv/www/vhosts/fluxgym/venv/bin/python
[2024-09-15 20:18:05] [INFO] Traceback (most recent call last):
[2024-09-15 20:18:05] [INFO] File "/srv/www/vhosts/fluxgym/venv/bin/accelerate", line 8, in <module>
[2024-09-15 20:18:05] [INFO] sys.exit(main())
[2024-09-15 20:18:05] [INFO] File "/srv/www/vhosts/fluxgym/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
[2024-09-15 20:18:05] [INFO] args.func(args)
[2024-09-15 20:18:05] [INFO] File "/srv/www/vhosts/fluxgym/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1091, in launch_command
[2024-09-15 20:18:05] [INFO] deepspeed_launcher(args)
[2024-09-15 20:18:05] [INFO] File "/srv/www/vhosts/fluxgym/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 787, in deepspeed_launcher
[2024-09-15 20:18:05] [INFO] distrib_run.run(args)
[2024-09-15 20:18:05] [INFO] File "/srv/www/vhosts/fluxgym/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
[2024-09-15 20:18:05] [INFO] elastic_launch(
[2024-09-15 20:18:05] [INFO] File "/srv/www/vhosts/fluxgym/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
[2024-09-15 20:18:05] [INFO] return launch_agent(self._config, self._entrypoint, list(args))
[2024-09-15 20:18:05] [INFO] File "/srv/www/vhosts/fluxgym/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
[2024-09-15 20:18:05] [INFO] raise ChildFailedError(
[2024-09-15 20:18:05] [INFO] torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
[2024-09-15 20:18:05] [INFO] ============================================================
[2024-09-15 20:18:05] [INFO] sd-scripts/flux_train_network.py FAILED
[2024-09-15 20:18:05] [INFO] ------------------------------------------------------------
[2024-09-15 20:18:05] [INFO] Failures:
[2024-09-15 20:18:05] [INFO] <NO_OTHER_FAILURES>
[2024-09-15 20:18:05] [INFO] ------------------------------------------------------------
[2024-09-15 20:18:05] [INFO] Root Cause (first observed failure):
[2024-09-15 20:18:05] [INFO] [0]:
[2024-09-15 20:18:05] [INFO] time      : 2024-09-15_20:18:05
[2024-09-15 20:18:05] [INFO] host      : mule.byteconcepts.com
[2024-09-15 20:18:05] [INFO] rank      : 0 (local_rank: 0)
[2024-09-15 20:18:05] [INFO] exitcode  : 1 (pid: 5881)
[2024-09-15 20:18:05] [INFO] error_file: <N/A>
[2024-09-15 20:18:05] [INFO] traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2024-09-15 20:18:05] [INFO] ============================================================
[2024-09-15 20:18:06] [ERROR] Command exited with code 1
[2024-09-15 20:18:06] [INFO] Runner: <LogsViewRunner nb_logs=149 exit_code=1>
```
Any ideas?

**Comment by starbuck100** [comment]
same here

**Comment by yunjiallm** [comment]
same here
