### ISSUE TITLE
WHY??CRY~~~

### ISSUE THREAD

**Issue by wuliang19869312** [cocktailpeanut/fluxgym#88]
[2024-09-16 10:50:28] [INFO] 2024-09-16 10:50:28 INFO     move vae and unet to cpu flux_train_network.py:208
[2024-09-16 10:50:28] [INFO] to save memory
[2024-09-16 10:50:28] [INFO] INFO     move text encoders to    flux_train_network.py:216
[2024-09-16 10:50:28] [INFO] gpu
[2024-09-16 10:50:31] [INFO] Traceback (most recent call last):
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\sd-scripts\flux_train_network.py", line 519, in <module>
[2024-09-16 10:50:31] [INFO] trainer.train(args)
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\sd-scripts\train_network.py", line 402, in train
[2024-09-16 10:50:31] [INFO] self.cache_text_encoder_outputs_if_needed(args, accelerator, unet, vae, text_encoders, train_dataset_group, weight_dtype)
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\sd-scripts\flux_train_network.py", line 218, in cache_text_encoder_outputs_if_needed
[2024-09-16 10:50:31] [INFO] text_encoders[1].to(accelerator.device)
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\env\Lib\site-packages\transformers\modeling_utils.py", line 2883, in to
[2024-09-16 10:50:31] [INFO] return super().to(*args, **kwargs)
[2024-09-16 10:50:31] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\env\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
[2024-09-16 10:50:31] [INFO] return self._apply(convert)
[2024-09-16 10:50:31] [INFO] ^^^^^^^^^^^^^^^^^^^^
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\env\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
[2024-09-16 10:50:31] [INFO] module._apply(fn)
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\env\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
[2024-09-16 10:50:31] [INFO] module._apply(fn)
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\env\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
[2024-09-16 10:50:31] [INFO] module._apply(fn)
[2024-09-16 10:50:31] [INFO] [Previous line repeated 4 more times]
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\env\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
[2024-09-16 10:50:31] [INFO] param_applied = fn(param)
[2024-09-16 10:50:31] [INFO] ^^^^^^^^^
[2024-09-16 10:50:31] [INFO] File "D:\fluxgym\env\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
[2024-09-16 10:50:31] [INFO] return t.to(
[2024-09-16 10:50:31] [INFO] ^^^^^
[2024-09-16 10:50:31] [INFO] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 11.99 GiB of which 9.09 GiB is free. Of the allocated memory 1.65 GiB is allocated by PyTorch, and 14.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-09-16 10:50:33] [INFO] Traceback (most recent call last):
[2024-09-16 10:50:33] [INFO] File "<frozen runpy>", line 198, in _run_module_as_main
[2024-09-16 10:50:33] [INFO] File "<frozen runpy>", line 88, in _run_code
[2024-09-16 10:50:33] [INFO] File "D:\fluxgym\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-09-16 10:50:33] [INFO] File "D:\fluxgym\env\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-09-16 10:50:33] [INFO] args.func(args)
[2024-09-16 10:50:33] [INFO] File "D:\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-09-16 10:50:33] [INFO] simple_launcher(args)
[2024-09-16 10:50:33] [INFO] File "D:\fluxgym\env\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-09-16 10:50:33] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-09-16 10:50:33] [INFO] subprocess.CalledProcessError: Command '['D:\\fluxgym\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'D:\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'D:\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'D:\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'D:\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '8', '--save_every_n_epochs', '4', '--dataset_config', 'D:\\fluxgym\\dataset.toml', '--output_dir', 'D:\\fluxgym\\outputs', '--output_name', 'dsps', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 1.
[2024-09-16 10:50:34] [ERROR] Command exited with code 1
[2024-09-16 10:50:34] [INFO] Runner: <LogsViewRunner nb_logs=158 exit_code=1>

**Comment by byteconcepts** [comment]
I see the parameter --highvram in the script call.
I don't have fluxgym active beacaus of another error at the moment but maybe there's a flag for lowvram which should be appropriate for your GPU?

**Comment by KnightOfMensab** [comment]
@wuliang19869312 Can you please let us know how you resolved this issue? I am experiencing the same behavior.
